// spot@public.miniTicker.v3.api

syntax = "proto3";

option go_package = "github.com/thrasher-corp/gocryptotrader/exchanges/mexc/mexc_proto_types";
option java_multiple_files = true;
option java_outer_classname = "PublicMiniTickerV3ApiProto";
option java_package = "com.mxc.push.common.protobuf";
option optimize_for = SPEED;

message PublicMiniTickerV3Api {
  // Symbol
  string symbol = 1;
  // Last price
  string price = 2;
  // Price change rate in UTC+8
  string rate = 3;
  // Price change rate in the requested time zone
  string zonedRate = 4;
  // Rolling high price
  string high = 5;
  // Rolling low price
  string low = 6;
  // Rolling quote volume
  string volume = 7;
  // Rolling base volume
  string quantity = 8;
  // Price change rate in UTC+8 against the previous close
  string lastCloseRate = 9;
  // Price change rate in the requested time zone against the previous close
  string lastCloseZonedRate = 10;
  // Rolling high price against the previous close
  string lastCloseHigh = 11;
  // Rolling low price against the previous close
  string lastCloseLow = 12;
}
