run:
  timeout: 1m30s
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - web/
    - testdata

linters:
  disable-all: true
  enable:
# defaults
#   - deadcode
#   - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
#   - unused
#   - varcheck

# disabled by default linters
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
#   - dupl
#   - exhaustive
    - exportloopref
#   - funlen
    - gci
#   - gochecknoglobals
#   - gochecknoinits
#   - gocognit
    - goconst
    - gocritic
#   - gocyclo
#   - godot
#   - godox
#   - goerr113
    - gofmt
#   - gofumpt
    - goheader
    - goimports
    - golint
#   - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
#   - interfacer
#   - lll
#   - maligned
    - misspell
    - nakedret
#   - nestif
#   - nlreturn
#   - noctx
    - nolintlint
#   - prealloc
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - stylecheck
#   - testpackage
    - unconvert
    - unparam
    - whitespace
#   - wsl

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  goconst:
    min-occurrences: 6
  depguard:
    list-type: blacklist
#  lll:
#    line-length: 80 # NOTE: we'll enforce this at a later point
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - importShadow
      - methodExprCall
      - evalOrder

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - text: "Expect WriteFile permissions to be 0600 or less"
      linters:
        - gosec