// Code generated by SQLBoiler 3.5.0-gct (https://github.com/thrasher-corp/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlite3

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AuditEvents", testAuditEvents)
	t.Run("Scripts", testScripts)
	t.Run("ScriptExecutions", testScriptExecutions)
}

func TestDelete(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsDelete)
	t.Run("Scripts", testScriptsDelete)
	t.Run("ScriptExecutions", testScriptExecutionsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsQueryDeleteAll)
	t.Run("Scripts", testScriptsQueryDeleteAll)
	t.Run("ScriptExecutions", testScriptExecutionsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsSliceDeleteAll)
	t.Run("Scripts", testScriptsSliceDeleteAll)
	t.Run("ScriptExecutions", testScriptExecutionsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsExists)
	t.Run("Scripts", testScriptsExists)
	t.Run("ScriptExecutions", testScriptExecutionsExists)
}

func TestFind(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsFind)
	t.Run("Scripts", testScriptsFind)
	t.Run("ScriptExecutions", testScriptExecutionsFind)
}

func TestBind(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsBind)
	t.Run("Scripts", testScriptsBind)
	t.Run("ScriptExecutions", testScriptExecutionsBind)
}

func TestOne(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsOne)
	t.Run("Scripts", testScriptsOne)
	t.Run("ScriptExecutions", testScriptExecutionsOne)
}

func TestAll(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsAll)
	t.Run("Scripts", testScriptsAll)
	t.Run("ScriptExecutions", testScriptExecutionsAll)
}

func TestCount(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsCount)
	t.Run("Scripts", testScriptsCount)
	t.Run("ScriptExecutions", testScriptExecutionsCount)
}

func TestHooks(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsHooks)
	t.Run("Scripts", testScriptsHooks)
	t.Run("ScriptExecutions", testScriptExecutionsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsInsert)
	t.Run("AuditEvents", testAuditEventsInsertWhitelist)
	t.Run("Scripts", testScriptsInsert)
	t.Run("Scripts", testScriptsInsertWhitelist)
	t.Run("ScriptExecutions", testScriptExecutionsInsert)
	t.Run("ScriptExecutions", testScriptExecutionsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("ScriptExecutionToScriptUsingScript", testScriptExecutionToOneScriptUsingScript)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ScriptToScriptExecutions", testScriptToManyScriptExecutions)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("ScriptExecutionToScriptUsingScriptExecutions", testScriptExecutionToOneSetOpScriptUsingScript)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ScriptToScriptExecutions", testScriptToManyAddOpScriptExecutions)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsReload)
	t.Run("Scripts", testScriptsReload)
	t.Run("ScriptExecutions", testScriptExecutionsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsReloadAll)
	t.Run("Scripts", testScriptsReloadAll)
	t.Run("ScriptExecutions", testScriptExecutionsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsSelect)
	t.Run("Scripts", testScriptsSelect)
	t.Run("ScriptExecutions", testScriptExecutionsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsUpdate)
	t.Run("Scripts", testScriptsUpdate)
	t.Run("ScriptExecutions", testScriptExecutionsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AuditEvents", testAuditEventsSliceUpdateAll)
	t.Run("Scripts", testScriptsSliceUpdateAll)
	t.Run("ScriptExecutions", testScriptExecutionsSliceUpdateAll)
}
