// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuditTrails                  string
	ExchangePlatformTradeHistory string
	Exchanges                    string
	Keys                         string
	UserKeys                     string
	UserOrderHistory             string
	Users                        string
}{
	AuditTrails:                  "audit_trails",
	ExchangePlatformTradeHistory: "exchange_platform_trade_history",
	Exchanges:                    "exchanges",
	Keys:                         "keys",
	UserKeys:                     "user_keys",
	UserOrderHistory:             "user_order_history",
	Users:                        "users",
}
