package binance

import (
	"context"
	"errors"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/thrasher-corp/gocryptotrader/exchanges/request"
)

func TestRateLimit_Limit(t *testing.T) {
	t.Parallel()
	symbol := "BTC-USDT"

	testTable := map[string]struct {
		Expected request.EndpointLimit
		Limit    request.EndpointLimit
		Deadline time.Time
	}{
		"Open Orders":          {Expected: spotOpenOrdersSpecificRate, Limit: openOrdersLimit(symbol)},
		"Orderbook Depth 5":    {Expected: spotOrderbookDepth100Rate, Limit: orderbookLimit(5)},
		"Orderbook Depth 10":   {Expected: spotOrderbookDepth100Rate, Limit: orderbookLimit(10)},
		"Orderbook Depth 20":   {Expected: spotOrderbookDepth100Rate, Limit: orderbookLimit(20)},
		"Orderbook Depth 50":   {Expected: spotOrderbookDepth100Rate, Limit: orderbookLimit(50)},
		"Orderbook Depth 100":  {Expected: spotOrderbookDepth100Rate, Limit: orderbookLimit(100)},
		"Orderbook Depth 500":  {Expected: spotOrderbookDepth500Rate, Limit: orderbookLimit(500)},
		"Orderbook Depth 1000": {Expected: spotOrderbookDepth1000Rate, Limit: orderbookLimit(1000)},
		"Orderbook Depth 5000": {Expected: spotOrderbookDepth5000Rate, Limit: orderbookLimit(5000)},
		"Exceeds deadline":     {Expected: spotOrderbookDepth5000Rate, Limit: orderbookLimit(5000), Deadline: time.Now().Add(time.Nanosecond)},
	}

	rl, err := request.New("rateLimitTest", &http.Client{}, request.WithLimiter(GetRateLimits()))
	require.NoError(t, err)

	for name, tt := range testTable {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			exp, got := tt.Expected, tt.Limit
			if exp != got {
				t.Fatalf("incorrect limit applied for '%s': \nexp: %v\ngot: %v", name, exp, got)
			}

			ctx := t.Context()
			if !tt.Deadline.IsZero() {
				var cancel context.CancelFunc
				ctx, cancel = context.WithDeadline(ctx, tt.Deadline)
				defer cancel()
			}

			if err := rl.InitiateRateLimit(ctx, tt.Limit); err != nil && !errors.Is(err, context.DeadlineExceeded) {
				t.Fatalf("error applying rate limit: %v", err)
			}
		})
	}
}

func TestRateLimit_LimitStatic(t *testing.T) {
	t.Parallel()
	testTable := map[string]request.EndpointLimit{
		"Default":           spotDefaultRate,
		"Historical Trades": spotHistoricalTradesRate,
		"All Price Changes": spotTickerAllRate,
		"All Orders":        spotAllOrdersRate,

		"aggTradesRate":                                          aggTradesRate,
		"listenKeyRate":                                          listenKeyRate,
		"sapiDefaultRate":                                        sapiDefaultRate,
		"allCoinInfoRate":                                        allCoinInfoRate,
		"dailyAccountSnapshotRate":                               dailyAccountSnapshotRate,
		"fundWithdrawalRate":                                     fundWithdrawalRate,
		"withdrawalHistoryRate":                                  withdrawalHistoryRate,
		"spotExchangeInfo":                                       spotExchangeInfo,
		"spotHistoricalTradesRate":                               spotHistoricalTradesRate,
		"spotOrderbookDepth100Rate":                              spotOrderbookDepth100Rate,
		"spotOrderbookDepth500Rate":                              spotOrderbookDepth500Rate,
		"spotOrderbookDepth1000Rate":                             spotOrderbookDepth1000Rate,
		"spotOrderbookDepth5000Rate":                             spotOrderbookDepth5000Rate,
		"getRecentTradesListRate":                                getRecentTradesListRate,
		"getOldTradeLookupRate":                                  getOldTradeLookupRate,
		"spotOrderbookTickerAllRate":                             spotOrderbookTickerAllRate,
		"spotBookTickerRate":                                     spotBookTickerRate,
		"spotSymbolPriceAllRate":                                 spotSymbolPriceAllRate,
		"spotSymbolPriceRate":                                    spotSymbolPriceRate,
		"getAggregateTradeListRate":                              getAggregateTradeListRate,
		"getKlineRate":                                           getKlineRate,
		"getCurrentAveragePriceRate":                             getCurrentAveragePriceRate,
		"get24HrTickerPriceChangeStatisticsRate":                 get24HrTickerPriceChangeStatisticsRate,
		"getTickers20Rate":                                       getTickers20Rate,
		"getTickers100Rate":                                      getTickers100Rate,
		"getTickersMoreThan100Rate":                              getTickersMoreThan100Rate,
		"spotPriceChangeAllRate":                                 spotPriceChangeAllRate,
		"spotOpenOrdersAllRate":                                  spotOpenOrdersAllRate,
		"allCrossMarginFeeDataRate":                              allCrossMarginFeeDataRate,
		"allIsolatedMarginFeeDataRate":                           allIsolatedMarginFeeDataRate,
		"marginCurrentOrderCountUsageRate":                       marginCurrentOrderCountUsageRate,
		"depositAddressesRate":                                   depositAddressesRate,
		"dustTransferRate":                                       dustTransferRate,
		"assetDividendRecordRate":                                assetDividendRecordRate,
		"userUniversalTransferRate":                              userUniversalTransferRate,
		"userAssetsRate":                                         userAssetsRate,
		"busdConvertHistoryRate":                                 busdConvertHistoryRate,
		"busdConvertRate":                                        busdConvertRate,
		"cloudMiningPaymentAndRefundHistoryRate":                 cloudMiningPaymentAndRefundHistoryRate,
		"autoConvertingStableCoinsRate":                          autoConvertingStableCoinsRate,
		"getMinersListRate":                                      getMinersListRate,
		"getEarningsListRate":                                    getEarningsListRate,
		"extraBonusListRate":                                     extraBonusListRate,
		"getHashrateRescaleRate":                                 getHashrateRescaleRate,
		"getHashrateRescaleDetailRate":                           getHashrateRescaleDetailRate,
		"getHasrateRescaleRequestRate":                           getHasrateRescaleRequestRate,
		"cancelHashrateResaleConfigurationRate":                  cancelHashrateResaleConfigurationRate,
		"statisticsListRate":                                     statisticsListRate,
		"miningAccountListRate":                                  miningAccountListRate,
		"miningAccountEarningRate":                               miningAccountEarningRate,
		"getDepositAddressListInNetworkRate":                     getDepositAddressListInNetworkRate,
		"getUserWalletBalanceRate":                               getUserWalletBalanceRate,
		"getUserDelegationHistoryRate":                           getUserDelegationHistoryRate,
		"symbolDelistScheduleForSpotRate":                        symbolDelistScheduleForSpotRate,
		"withdrawAddressListRate":                                withdrawAddressListRate,
		"crossMarginCollateralRatioRate":                         crossMarginCollateralRatioRate,
		"smallLiabilityExchangeCoinListRate":                     smallLiabilityExchangeCoinListRate,
		"getSmallLiabilityExchangeCoinListRate":                  getSmallLiabilityExchangeCoinListRate,
		"getSmallLiabilityExchangeRate":                          getSmallLiabilityExchangeRate,
		"marginHourlyInterestRate":                               marginHourlyInterestRate,
		"marginCapitalFlowRate":                                  marginCapitalFlowRate,
		"marginTokensAndSymbolsDelistScheduleRate":               marginTokensAndSymbolsDelistScheduleRate,
		"marginAvailableInventoryRate":                           marginAvailableInventoryRate,
		"marginManualLiquidiationRate":                           marginManualLiquidiationRate,
		"getSubAccountAssetRate":                                 getSubAccountAssetRate,
		"getSubAccountStatusOnMarginOrFuturesRate":               getSubAccountStatusOnMarginOrFuturesRate,
		"marginAccountInformationRate":                           marginAccountInformationRate,
		"subAccountMarginAccountDetailRate":                      subAccountMarginAccountDetailRate,
		"getSubAccountSummaryOfMarginAccountRate":                getSubAccountSummaryOfMarginAccountRate,
		"getDetailSubAccountFuturesAccountRate":                  getDetailSubAccountFuturesAccountRate,
		"getFuturesPositionRiskOfSubAccountV1Rate":               getFuturesPositionRiskOfSubAccountV1Rate,
		"getFuturesSubAccountSummaryV2Rate":                      getFuturesSubAccountSummaryV2Rate,
		"ipRestrictionForSubAccountAPIKeyRate":                   ipRestrictionForSubAccountAPIKeyRate,
		"deleteIPListForSubAccountAPIKeyRate":                    deleteIPListForSubAccountAPIKeyRate,
		"addIPRestrictionSubAccountAPIKey":                       addIPRestrictionSubAccountAPIKey,
		"getManagedSubAccountSnapshotRate":                       getManagedSubAccountSnapshotRate,
		"managedSubAccountTransferLogRate":                       managedSubAccountTransferLogRate,
		"managedSubAccountFuturesAssetDetailRate":                managedSubAccountFuturesAssetDetailRate,
		"getManagedSubAccountListRate":                           getManagedSubAccountListRate,
		"getSubAccountTransactionStatisticsRate":                 getSubAccountTransactionStatisticsRate,
		"marginAccountBorrowRepayRate":                           marginAccountBorrowRepayRate,
		"getCrossMarginAccountDetailRate":                        getCrossMarginAccountDetailRate,
		"getCrossMarginAccountOrderRate":                         getCrossMarginAccountOrderRate,
		"getMarginAccountsOpenOrdersRate":                        getMarginAccountsOpenOrdersRate,
		"marginAccountsAllOrdersRate":                            marginAccountsAllOrdersRate,
		"marginAccountOpenOCOOrdersRate":                         marginAccountOpenOCOOrdersRate,
		"marginAccountTradeListRate":                             marginAccountTradeListRate,
		"marginMaxBorrowRate":                                    marginMaxBorrowRate,
		"maxTransferOutRate":                                     maxTransferOutRate,
		"marginAccountSummaryRate":                               marginAccountSummaryRate,
		"getIsolatedMarginAccountInfoRate":                       getIsolatedMarginAccountInfoRate,
		"deleteIsolatedMarginAccountRate":                        deleteIsolatedMarginAccountRate,
		"enableIsolatedMarginAccountRate":                        enableIsolatedMarginAccountRate,
		"allIsolatedMarginSymbol":                                allIsolatedMarginSymbol,
		"marginOCOOrderRate":                                     marginOCOOrderRate,
		"getMarginAccountOCOOrderRate":                           getMarginAccountOCOOrderRate,
		"getMarginAccountAllOCORate":                             getMarginAccountAllOCORate,
		"getOCOListRate":                                         getOCOListRate,
		"getAllOCOOrdersRate":                                    getAllOCOOrdersRate,
		"getOpenOCOListRate":                                     getOpenOCOListRate,
		"simpleEarnProductsRate":                                 simpleEarnProductsRate,
		"getSimpleEarnProductPositionRate":                       getSimpleEarnProductPositionRate,
		"simpleAccountRate":                                      simpleAccountRate,
		"getFlexibleSubscriptionRecordRate":                      getFlexibleSubscriptionRecordRate,
		"nftRate":                                                nftRate,
		"spotRebateHistoryRate":                                  spotRebateHistoryRate,
		"convertTradeFlowHistoryRate":                            convertTradeFlowHistoryRate,
		"getLimitOpenOrdersRate":                                 getLimitOpenOrdersRate,
		"cancelLimitOrderRate":                                   cancelLimitOrderRate,
		"placeLimitOrderRate":                                    placeLimitOrderRate,
		"orderStatusRate":                                        orderStatusRate,
		"acceptQuoteRate":                                        acceptQuoteRate,
		"sendQuoteRequestRate":                                   sendQuoteRequestRate,
		"getLockedSubscriptionRecordsRate":                       getLockedSubscriptionRecordsRate,
		"getRedemptionRecordRate":                                getRedemptionRecordRate,
		"getRewardHistoryRate":                                   getRewardHistoryRate,
		"setAutoSubscribeRate":                                   setAutoSubscribeRate,
		"personalLeftQuotaRate":                                  personalLeftQuotaRate,
		"subscriptionPreviewRate":                                subscriptionPreviewRate,
		"simpleEarnRateHistoryRate":                              simpleEarnRateHistoryRate,
		"etherumStakingRedemptionRate":                           etherumStakingRedemptionRate,
		"ethStakingHistoryRate":                                  ethStakingHistoryRate,
		"ethRedemptionHistoryRate":                               ethRedemptionHistoryRate,
		"bethRewardDistributionHistoryRate":                      bethRewardDistributionHistoryRate,
		"currentETHStakingQuotaRate":                             currentETHStakingQuotaRate,
		"getWBETHRateHistoryRate":                                getWBETHRateHistoryRate,
		"ethStakingAccountRate":                                  ethStakingAccountRate,
		"wrapBETHRate":                                           wrapBETHRate,
		"wbethWrapOrUnwrapHistoryRate":                           wbethWrapOrUnwrapHistoryRate,
		"wbethRewardsHistoryRate":                                wbethRewardsHistoryRate,
		"futuresFundTransfersFetchRate":                          futuresFundTransfersFetchRate,
		"futureTickLevelOrderbookHistoricalDataDownloadLinkRate": futureTickLevelOrderbookHistoricalDataDownloadLinkRate,
		"fundAutoCollectionRate":                                 fundAutoCollectionRate,
		"getAutoRepayFuturesStatusRate":                          getAutoRepayFuturesStatusRate,
		"pmAssetLeverageRate":                                    pmAssetLeverageRate,
		"getVIPLoanOngoingOrdersRate":                            getVIPLoanOngoingOrdersRate,
		"vipLoanRepayRate":                                       vipLoanRepayRate,
		"vipLoanRenewRate":                                       vipLoanRenewRate,
		"getVIPLoanRepaymentHistoryRate":                         getVIPLoanRepaymentHistoryRate,
		"checkLockedValueVIPCollateralAccountRate":               checkLockedValueVIPCollateralAccountRate,
		"vipLoanBorrowRate":                                      vipLoanBorrowRate,
		"getVIPLoanableAssetsRate":                               getVIPLoanableAssetsRate,
		"getCollateralAssetDataRate":                             getCollateralAssetDataRate,
		"getApplicationStatusRate":                               getApplicationStatusRate,
		"getVIPBorrowInterestRate":                               getVIPBorrowInterestRate,
		"fiatDepositWithdrawHistRate":                            fiatDepositWithdrawHistRate,
		"getAllConvertPairsRate":                                 getAllConvertPairsRate,
		"getOrderQuantityPrecisionPerAssetRate":                  getOrderQuantityPrecisionPerAssetRate,
		"testNewOrderWithCommissionRate":                         testNewOrderWithCommissionRate,
		"payTradeEndpointsRate":                                  payTradeEndpointsRate,
		"classicPMAccountInfoRate":                               classicPMAccountInfoRate,
		"classicPMCollateralRate":                                classicPMCollateralRate,
		"getClassicPMBankruptacyLoanAmountRate":                  getClassicPMBankruptacyLoanAmountRate,
		"repayClassicPMBankruptacyLoanRate":                      repayClassicPMBankruptacyLoanRate,
		"classicPMNegativeBalanceInterestHistory":                classicPMNegativeBalanceInterestHistory,
		"pmAssetIndexPriceRate":                                  pmAssetIndexPriceRate,
		"fundCollectionByAssetRate":                              fundCollectionByAssetRate,
		"transferBNBRate":                                        transferBNBRate,
		"changeAutoRepayFuturesStatusRate":                       changeAutoRepayFuturesStatusRate,
		"repayFuturesNegativeBalanceRate":                        repayFuturesNegativeBalanceRate,
		"spotTwapNewOrderRate":                                   spotTwapNewOrderRate,
		"subscribeETHStakingRate":                                subscribeETHStakingRate,
		"placeVPOrderRate":                                       placeVPOrderRate,
		"placeTWAveragePriceNewOrderRate":                        placeTWAveragePriceNewOrderRate,
		"spotOpenOrdersSpecificRate":                             spotOpenOrdersSpecificRate,
		"spotOrderRate":                                          spotOrderRate,
		"spotOrderQueryRate":                                     spotOrderQueryRate,
		"spotAllOrdersRate":                                      spotAllOrdersRate,
		"spotAccountInformationRate":                             spotAccountInformationRate,
		"accountTradeListRate":                                   accountTradeListRate,
		"currentOrderCountUsageRate":                             currentOrderCountUsageRate,
		"queryPreventedMatchsWithRate":                           queryPreventedMatchsWithRate,
		"getAllocationsRate":                                     getAllocationsRate,
		"preventedMatchesByOrderIDRate":                          preventedMatchesByOrderIDRate,
		"getCommissionRate":                                      getCommissionRate,
		"borrowRepayRecordsInMarginAccountRate":                  borrowRepayRecordsInMarginAccountRate,
		"getPriceMarginIndexRate":                                getPriceMarginIndexRate,
		"marginAccountNewOrderRate":                              marginAccountNewOrderRate,
		"marginAccountCancelOrderRate":                           marginAccountCancelOrderRate,
		"adjustCrossMarginMaxLeverageRate":                       adjustCrossMarginMaxLeverageRate,
		"uFuturesDefaultRate":                                    uFuturesDefaultRate,
		"uFuturesHistoricalTradesRate":                           uFuturesHistoricalTradesRate,
		"uFuturesSymbolOrdersRate":                               uFuturesSymbolOrdersRate,
		"uFuturesPairOrdersRate":                                 uFuturesPairOrdersRate,
		"uFuturesCurrencyForceOrdersRate":                        uFuturesCurrencyForceOrdersRate,
		"uFuturesAllForceOrdersRate":                             uFuturesAllForceOrdersRate,
		"uFuturesIncomeHistoryRate":                              uFuturesIncomeHistoryRate,
		"uFuturesOrderbook50Rate":                                uFuturesOrderbook50Rate,
		"uFuturesOrderbook100Rate":                               uFuturesOrderbook100Rate,
		"uFuturesOrderbook500Rate":                               uFuturesOrderbook500Rate,
		"uFuturesOrderbook1000Rate":                              uFuturesOrderbook1000Rate,
		"uFuturesKline100Rate":                                   uFuturesKline100Rate,
		"uFuturesKline500Rate":                                   uFuturesKline500Rate,
		"uFuturesKline1000Rate":                                  uFuturesKline1000Rate,
		"uFuturesKlineMaxRate":                                   uFuturesKlineMaxRate,
		"uFuturesTickerPriceHistoryRate":                         uFuturesTickerPriceHistoryRate,
		"uFuturesOrdersDefaultRate":                              uFuturesOrdersDefaultRate,
		"uFuturesGetAllOrdersRate":                               uFuturesGetAllOrdersRate,
		"uFuturesAccountInformationRate":                         uFuturesAccountInformationRate,
		"uFuturesOrderbookTickerAllRate":                         uFuturesOrderbookTickerAllRate,
		"uFuturesCountdownCancelRate":                            uFuturesCountdownCancelRate,
		"uFuturesBatchOrdersRate":                                uFuturesBatchOrdersRate,
		"uFuturesGetAllOpenOrdersRate":                           uFuturesGetAllOpenOrdersRate,
		"cFuturesDefaultRate":                                    cFuturesDefaultRate,
		"cFuturesHistoricalTradesRate":                           cFuturesHistoricalTradesRate,
		"cFuturesTickerPriceHistoryRate":                         cFuturesTickerPriceHistoryRate,
		"cFuturesIncomeHistoryRate":                              cFuturesIncomeHistoryRate,
		"cFuturesOrderbook50Rate":                                cFuturesOrderbook50Rate,
		"cFuturesOrderbook100Rate":                               cFuturesOrderbook100Rate,
		"cFuturesOrderbook500Rate":                               cFuturesOrderbook500Rate,
		"cFuturesOrderbook1000Rate":                              cFuturesOrderbook1000Rate,
		"cFuturesKline100Rate":                                   cFuturesKline100Rate,
		"cFuturesKline500Rate":                                   cFuturesKline500Rate,
		"cFuturesKline1000Rate":                                  cFuturesKline1000Rate,
		"cFuturesKlineMaxRate":                                   cFuturesKlineMaxRate,
		"cFuturesIndexMarkPriceRate":                             cFuturesIndexMarkPriceRate,
		"cFuturesBatchOrdersRate":                                cFuturesBatchOrdersRate,
		"cFuturesCancelAllOrdersRate":                            cFuturesCancelAllOrdersRate,
		"cFuturesGetAllOpenOrdersRate":                           cFuturesGetAllOpenOrdersRate,
		"cFuturesAllForceOrdersRate":                             cFuturesAllForceOrdersRate,
		"cFuturesCurrencyForceOrdersRate":                        cFuturesCurrencyForceOrdersRate,
		"cFuturesPairOrdersRate":                                 cFuturesPairOrdersRate,
		"cFuturesSymbolOrdersRate":                               cFuturesSymbolOrdersRate,
		"cFuturesAccountInformationRate":                         cFuturesAccountInformationRate,
		"cFuturesOrderbookTickerAllRate":                         cFuturesOrderbookTickerAllRate,
		"cFuturesOrdersDefaultRate":                              cFuturesOrdersDefaultRate,
		"uFuturesMultiAssetMarginRate":                           uFuturesMultiAssetMarginRate,
		"uFuturesSetMultiAssetMarginRate":                        uFuturesSetMultiAssetMarginRate,
		"optionsDefaultRate":                                     optionsDefaultRate,
		"optionsRecentTradesRate":                                optionsRecentTradesRate,
		"optionsHistoricalTradesRate":                            optionsHistoricalTradesRate,
		"optionsMarkPriceRate":                                   optionsMarkPriceRate,
		"optionsAllTickerPriceStatistics":                        optionsAllTickerPriceStatistics,
		"optionsHistoricalExerciseRecordsRate":                   optionsHistoricalExerciseRecordsRate,
		"optionsAccountInfoRate":                                 optionsAccountInfoRate,
		"optionsDefaultOrderRate":                                optionsDefaultOrderRate,
		"optionsBatchOrderRate":                                  optionsBatchOrderRate,
		"optionsAllQueryOpenOrdersRate":                          optionsAllQueryOpenOrdersRate,
		"optionsGetOrderHistory":                                 optionsGetOrderHistory,
		"optionsPositionInformationRate":                         optionsPositionInformationRate,
		"optionsAccountTradeListRate":                            optionsAccountTradeListRate,
		"optionsUserExerciseRecordRate":                          optionsUserExerciseRecordRate,
		"optionsDownloadIDForOptionTrasactionHistoryRate":        optionsDownloadIDForOptionTrasactionHistoryRate,
		"optionsGetTransHistoryDownloadLinkByIDRate":             optionsGetTransHistoryDownloadLinkByIDRate,
		"optionsMarginAccountInfoRate":                           optionsMarginAccountInfoRate,
		"optionsAutoCancelAllOpenOrdersHeartbeatRate":            optionsAutoCancelAllOpenOrdersHeartbeatRate,
		"pmDefaultRate":                                          pmDefaultRate,
		"pmMarginAccountLoanAndRepayRate":                        pmMarginAccountLoanAndRepayRate,
		"pmCancelMarginAccountOpenOrdersOnSymbolRate":            pmCancelMarginAccountOpenOrdersOnSymbolRate,
		"pmCancelMarginAccountOCORate":                           pmCancelMarginAccountOCORate,
		"pmRetrieveAllUMOpenOrdersForAllSymbolRate":              pmRetrieveAllUMOpenOrdersForAllSymbolRate,
		"pmGetAllUMOrdersRate":                                   pmGetAllUMOrdersRate,
		"pmRetrieveAllCMOpenOrdersForAllSymbolRate":              pmRetrieveAllCMOpenOrdersForAllSymbolRate,
		"pmAllCMOrderWithSymbolRate":                             pmAllCMOrderWithSymbolRate,
		"pmAllCMOrderWithoutSymbolRate":                          pmAllCMOrderWithoutSymbolRate,
		"pmUMOpenConditionalOrdersRate":                          pmUMOpenConditionalOrdersRate,
		"pmAllUMConditionalOrdersWithoutSymbolRate":              pmAllUMConditionalOrdersWithoutSymbolRate,
		"pmAllCMOpenConditionalOrdersWithoutSymbolRate":          pmAllCMOpenConditionalOrdersWithoutSymbolRate,
		"pmAllCMConditionalOrderWithoutSymbolRate":               pmAllCMConditionalOrderWithoutSymbolRate,
		"pmGetMarginAccountOrderRate":                            pmGetMarginAccountOrderRate,
		"pmCurrentMarginOpenOrderRate":                           pmCurrentMarginOpenOrderRate,
		"pmAllMarginAccountOrdersRate":                           pmAllMarginAccountOrdersRate,
		"pmGetMarginAccountOCORate":                              pmGetMarginAccountOCORate,
		"pmGetMarginAccountsAllOCOOrdersRate":                    pmGetMarginAccountsAllOCOOrdersRate,
		"pmGetMarginAccountsOpenOCOOrdersRate":                   pmGetMarginAccountsOpenOCOOrdersRate,
		"pmGetMarginAccountTradeListRate":                        pmGetMarginAccountTradeListRate,
		"pmGetAccountBalancesRate":                               pmGetAccountBalancesRate,
		"pmGetAccountInformationRate":                            pmGetAccountInformationRate,
		"pmMarginMaxBorrowRate":                                  pmMarginMaxBorrowRate,
		"pmGetMarginMaxWithdrawalRate":                           pmGetMarginMaxWithdrawalRate,
		"pmGetUMPositionInformationRate":                         pmGetUMPositionInformationRate,
		"pmGetUMCurrentPositionModeRate":                         pmGetUMCurrentPositionModeRate,
		"pmGetCMCurrentPositionModeRate":                         pmGetCMCurrentPositionModeRate,
		"pmGetUMAccountTradeListRate":                            pmGetUMAccountTradeListRate,
		"pmGetCMAccountTradeListWithSymbolRate":                  pmGetCMAccountTradeListWithSymbolRate,
		"pmGetCMAccountTradeListWithPairRate":                    pmGetCMAccountTradeListWithPairRate,
		"pmGetUserUMForceOrdersWithSymbolRate":                   pmGetUserUMForceOrdersWithSymbolRate,
		"pmGetUserUMForceOrdersWithoutSymbolRate":                pmGetUserUMForceOrdersWithoutSymbolRate,
		"pmGetUserCMForceOrdersWithSymbolRate":                   pmGetUserCMForceOrdersWithSymbolRate,
		"pmGetUserCMForceOrdersWithoutSymbolRate":                pmGetUserCMForceOrdersWithoutSymbolRate,
		"pmUMTradingQuantitativeRulesIndicatorsRate":             pmUMTradingQuantitativeRulesIndicatorsRate,
		"pmGetUMUserCommissionRate":                              pmGetUMUserCommissionRate,
		"pmGetCMUserCommissionRate":                              pmGetCMUserCommissionRate,
		"pmGetMarginLoanRecordRate":                              pmGetMarginLoanRecordRate,
		"pmGetMarginRepayRecordRate":                             pmGetMarginRepayRecordRate,
		"pmGetPortfolioMarginNegativeBalanceInterestHistoryRate": pmGetPortfolioMarginNegativeBalanceInterestHistoryRate,
		"pmFundAutoCollectionRate":                               pmFundAutoCollectionRate,
		"pmFundCollectionByAssetRate":                            pmFundCollectionByAssetRate,
		"pmBNBTransferRate":                                      pmBNBTransferRate,
		"pmGetUMIncomeHistoryRate":                               pmGetUMIncomeHistoryRate,
		"pmGetCMIncomeHistoryRate":                               pmGetCMIncomeHistoryRate,
		"pmGetUMAccountDetailRate":                               pmGetUMAccountDetailRate,
		"pmGetCMAccountDetailRate":                               pmGetCMAccountDetailRate,
		"pmChangeAutoRepayFuturesStatusRate":                     pmChangeAutoRepayFuturesStatusRate,
		"pmGetAutoRepayFuturesStatusRate":                        pmGetAutoRepayFuturesStatusRate,
		"pmRepayFuturesNegativeBalanceRate":                      pmRepayFuturesNegativeBalanceRate,
		"pmGetUMPositionADLQuantileEstimationRate":               pmGetUMPositionADLQuantileEstimationRate,
		"pmGetCMPositionADLQuantileEstimationRate":               pmGetCMPositionADLQuantileEstimationRate,
		"getFlexibleSimpleEarnProductPositionRate":               getFlexibleSimpleEarnProductPositionRate,
		"cryptoLoansIncomeHistory":                               cryptoLoansIncomeHistory,
		"getLoanBorrowHistoryRate":                               getLoanBorrowHistoryRate,
		"getBorrowOngoingOrdersRate":                             getBorrowOngoingOrdersRate,
		"cryptoRepayLoanRate":                                    cryptoRepayLoanRate,
		"repaymentHistoryRate":                                   repaymentHistoryRate,
		"adjustLTVRate":                                          adjustLTVRate,
		"getLoanLTVAdjustmentHistoryRate":                        getLoanLTVAdjustmentHistoryRate,
		"getLoanableAssetsDataRate":                              getLoanableAssetsDataRate,
		"collateralAssetsDataRate":                               collateralAssetsDataRate,
		"checkCollateralRepayRate":                               checkCollateralRepayRate,
		"cryptoLoanCustomizeMarginRate":                          cryptoLoanCustomizeMarginRate,
		"borrowFlexibleRate":                                     borrowFlexibleRate,
		"getFlexibleLoanOngoingOrdersRate":                       getFlexibleLoanOngoingOrdersRate,
		"flexibleBorrowHistoryRate":                              flexibleBorrowHistoryRate,
		"repayFlexibleLoanHistoryRate":                           repayFlexibleLoanHistoryRate,
		"flexibleLoanRepaymentHistoryRate":                       flexibleLoanRepaymentHistoryRate,
		"flexibleLoanCollateralRepaymentRate":                    flexibleLoanCollateralRepaymentRate,
		"adjustFlexibleLoanRate":                                 adjustFlexibleLoanRate,
		"flexibleLoanAdjustLTVRate":                              flexibleLoanAdjustLTVRate,
		"flexibleLoanAssetDataRate":                              flexibleLoanAssetDataRate,
		"flexibleLoanCollateralAssetRate":                        flexibleLoanCollateralAssetRate,
		"flexibleLoanLiquidiationHistoryRate":                    flexibleLoanLiquidiationHistoryRate,
		"solStakingAccountRate":                                  solStakingAccountRate,
		"solStakingQuotaDetailsRate":                             solStakingQuotaDetailsRate,
		"subscribeSOLStakingRate":                                subscribeSOLStakingRate,
		"redeemSOLRate":                                          redeemSOLRate,
		"claimbBoostReqardsRate":                                 claimbBoostReqardsRate,
		"solStakingHistoryRate":                                  solStakingHistoryRate,
		"solRedemptionHistoryRate":                               solRedemptionHistoryRate,
		"bnsolRewardsHistoryRate":                                bnsolRewardsHistoryRate,
		"bnsolRateHistory":                                       bnsolRateHistory,
		"boostRewardsHistoryRate":                                boostRewardsHistoryRate,
		"unclaimedRewardsRate":                                   unclaimedRewardsRate,
		"createSubAccountRate":                                   createSubAccountRate,
		"getSubAccountRate":                                      getSubAccountRate,
		"enableFuturesForSubAccountRate":                         enableFuturesForSubAccountRate,
		"createAPIKeyForSubAccountRate":                          createAPIKeyForSubAccountRate,
	}

	rl, err := request.New("rateLimitTest2", http.DefaultClient, request.WithLimiter(GetRateLimits()))
	require.NoError(t, err)

	for name, tt := range testTable {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			if err := rl.InitiateRateLimit(t.Context(), tt); err != nil {
				t.Fatalf("error applying rate limit: %v", err)
			}
		})
	}
}
