package yobit

import (
	"github.com/thrasher-corp/gocryptotrader/currency"
	exchange "github.com/thrasher-corp/gocryptotrader/exchanges"
	"github.com/thrasher-corp/gocryptotrader/exchanges/asset"
	"github.com/thrasher-corp/gocryptotrader/exchanges/fee"
)

// Response is a generic struct used for exchange API request result
type Response struct {
	Return  interface{} `json:"return"`
	Success int         `json:"success"`
	Error   string      `json:"error"`
}

// Info holds server time and pair information
type Info struct {
	ServerTime int64           `json:"server_time"`
	Pairs      map[string]Pair `json:"pairs"`
}

// Ticker stores the ticker information
type Ticker struct {
	High          float64 // maximal price
	Low           float64 // minimal price
	Avg           float64 // average price
	Vol           float64 // traded volume
	VolumeCurrent float64 `json:"vol_cur"` // traded volume in currency
	Last          float64 // last transaction price
	Buy           float64 // buying price
	Sell          float64 // selling price
	Updated       int64   // last cache upgrade
}

// Orderbook stores the asks and bids orderbook information
type Orderbook struct {
	Asks [][]float64 `json:"asks"` // selling orders
	Bids [][]float64 `json:"bids"` // buying orders
}

// Trade stores trade information
type Trade struct {
	Type      string  `json:"type"`
	Price     float64 `json:"price"`
	Amount    float64 `json:"amount"`
	TID       int64   `json:"tid"`
	Timestamp int64   `json:"timestamp"`
}

// ActiveOrders stores active order information
type ActiveOrders struct {
	Pair             string  `json:"pair"`
	Type             string  `json:"type"`
	Amount           float64 `json:"amount"`
	Rate             float64 `json:"rate"`
	TimestampCreated float64 `json:"timestamp_created"`
	Status           int     `json:"status"`
}

// Pair holds pair information
type Pair struct {
	DecimalPlaces int     `json:"decimal_places"` // Quantity of permitted numbers after decimal point
	MinPrice      float64 `json:"min_price"`      // Minimal permitted price
	MaxPrice      float64 `json:"max_price"`      // Maximal permitted price
	MinAmount     float64 `json:"min_amount"`     // Minimal permitted buy or sell amount
	Hidden        int     `json:"hidden"`         // Pair is hidden (0 or 1)
	Fee           float64 `json:"fee"`            // Pair commission
}

// AccountInfo stores the account information for a user
type AccountInfo struct {
	Funds           map[string]float64 `json:"funds"`
	FundsInclOrders map[string]float64 `json:"funds_incl_orders"`
	Rights          struct {
		Info     int `json:"info"`
		Trade    int `json:"trade"`
		Withdraw int `json:"withdraw"`
	} `json:"rights"`
	TransactionCount int     `json:"transaction_count"`
	OpenOrders       int     `json:"open_orders"`
	ServerTime       float64 `json:"server_time"`
	Error            string  `json:"error"`
}

// OrderInfo stores order information
type OrderInfo struct {
	Pair             string  `json:"pair"`
	Type             string  `json:"type"`
	StartAmount      float64 `json:"start_amount"`
	Amount           float64 `json:"amount"`
	Rate             float64 `json:"rate"`
	TimestampCreated float64 `json:"timestamp_created"`
	Status           int     `json:"status"`
}

// CancelOrder is used for the CancelOrder API request response
type CancelOrder struct {
	OrderID float64            `json:"order_id"`
	Funds   map[string]float64 `json:"funds"`
	Error   string             `json:"error"`
}

// TradeOrderResponse stores the trade information
type TradeOrderResponse struct {
	Received float64            `json:"received"`
	Remains  float64            `json:"remains"`
	OrderID  float64            `json:"order_id"`
	Funds    map[string]float64 `json:"funds"`
	Error    string             `json:"error"`
}

// TradeHistoryResponse returns all your trade history
type TradeHistoryResponse struct {
	Success int64                   `json:"success"`
	Data    map[string]TradeHistory `json:"return,omitempty"`
	Error   string                  `json:"error,omitempty"`
}

// TradeHistory stores trade history
type TradeHistory struct {
	Pair      string  `json:"pair"`
	Type      string  `json:"type"`
	Amount    float64 `json:"amount"`
	Rate      float64 `json:"rate"`
	OrderID   float64 `json:"order_id"`
	MyOrder   int     `json:"is_your_order"`
	Timestamp float64 `json:"timestamp"`
}

// DepositAddress stores a curency deposit address
type DepositAddress struct {
	Success int `json:"success"`
	Return  struct {
		Address         string  `json:"address"`
		ProcessedAmount float64 `json:"processed_amount"`
		ServerTime      int64   `json:"server_time"`
	} `json:"return"`
	Error string `json:"error"`
}

// WithdrawCoinsToAddress stores information for a withdrawcoins request
type WithdrawCoinsToAddress struct {
	ServerTime int64  `json:"server_time"`
	Error      string `json:"error"`
}

// CreateCoupon stores information coupon information
type CreateCoupon struct {
	Coupon  string             `json:"coupon"`
	TransID int64              `json:"transID"`
	Funds   map[string]float64 `json:"funds"`
	Error   string             `json:"error"`
}

// RedeemCoupon stores redeem coupon information
type RedeemCoupon struct {
	CouponAmount   float64            `json:"couponAmount,string"`
	CouponCurrency string             `json:"couponCurrency"`
	TransID        int64              `json:"transID"`
	Funds          map[string]float64 `json:"funds"`
	Error          string             `json:"error"`
}

// internationBank the list of predefined withdrawal fees for international
// bank transfers.
var internationBank = map[fee.InternationalBankTransaction]map[currency.Code]fee.Transfer{
	exchange.PerfectMoney: {currency.USD: {Withdrawal: 0.02, IsPercentage: true}},
	exchange.Payeer: {
		currency.USD: {Withdrawal: 0.03, IsPercentage: true},
		currency.RUR: {Withdrawal: 0.006, IsPercentage: true},
	},
	exchange.AdvCash: {
		currency.USD: {Withdrawal: 0.04, IsPercentage: true},
		currency.RUR: {Withdrawal: 0.03, IsPercentage: true},
	},
	exchange.Qiwi:       {currency.RUR: {Withdrawal: 0.04, IsPercentage: true}},
	exchange.Capitalist: {currency.RUR: {Withdrawal: 0.06, IsPercentage: true}},
}

// withdrawalFees the large list of predefined withdrawal fees
// Prone to change, using highest value
var withdrawalFees = map[asset.Item]map[currency.Code]fee.Transfer{
	asset.Spot: {
		currency.ZERO07:     {Withdrawal: 0.002, IsPercentage: true},
		currency.BIT16:      {Withdrawal: 0.002, IsPercentage: true},
		currency.TWO015:     {Withdrawal: 0.002, IsPercentage: true},
		currency.TWO56:      {Withdrawal: 0.0002, IsPercentage: true},
		currency.TWOBACCO:   {Withdrawal: 0.002, IsPercentage: true},
		currency.TWOGIVE:    {Withdrawal: 0.01, IsPercentage: true},
		currency.THIRTY2BIT: {Withdrawal: 0.002, IsPercentage: true},
		currency.THREE65:    {Withdrawal: 0.01, IsPercentage: true},
		currency.FOUR04:     {Withdrawal: 0.01, IsPercentage: true},
		currency.SEVEN00:    {Withdrawal: 0.01, IsPercentage: true},
		currency.EIGHTBIT:   {Withdrawal: 0.002, IsPercentage: true},
		currency.ACLR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ACES:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ACPR:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ACID:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ACOIN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.ACRN:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ADAM:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ADT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.AIB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ADZ:        {Withdrawal: 0.002, IsPercentage: true},
		currency.AECC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.AM:         {Withdrawal: 0.002, IsPercentage: true},
		currency.AE:         {Withdrawal: 10, IsPercentage: true},
		currency.DLT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.AGRI:       {Withdrawal: 0.01, IsPercentage: true},
		currency.AGT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.AST:        {Withdrawal: 0.002, IsPercentage: true},
		currency.AIR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ALEX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.AUM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ALIEN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.ALIS:       {Withdrawal: 0.05, IsPercentage: true},
		currency.ALL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ASAFE:      {Withdrawal: 0.01, IsPercentage: true},
		currency.AMBER:      {Withdrawal: 0.002, IsPercentage: true},
		currency.AMS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ANAL:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ACP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ANI:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ANTI:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ALTC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.APT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ARCO:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ALC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ANT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ARB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ARCT:       {Withdrawal: 10, IsPercentage: true},
		currency.ARCX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ARGUS:      {Withdrawal: 0.01, IsPercentage: true},
		currency.ARH:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ARM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ARNA:       {Withdrawal: 10, IsPercentage: true},
		currency.ARPA:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ARTA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ABY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ARTC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.AL:         {Withdrawal: 0.01, IsPercentage: true},
		currency.ASN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ADCN:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ATB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ATL:        {Withdrawal: 0.1, IsPercentage: true},
		currency.ATM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ATMCHA:     {Withdrawal: 0.05, IsPercentage: true},
		currency.ATOM:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ADC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.REP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ARE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.AUR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.AV:         {Withdrawal: 0.002, IsPercentage: true},
		currency.AXIOM:      {Withdrawal: 0.002, IsPercentage: true},
		currency.B2B:        {Withdrawal: 10, IsPercentage: true},
		currency.B2:         {Withdrawal: 0.01, IsPercentage: true},
		currency.B3:         {Withdrawal: 0.1, IsPercentage: true},
		currency.BAB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BAN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BamitCoin:  {Withdrawal: 0.002, IsPercentage: true},
		currency.NANAS:      {Withdrawal: 0.002, IsPercentage: true},
		currency.BNT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.BBCC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BAT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.BTA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BSTK:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BATL:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BBH:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BITB:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BRDD:       {Withdrawal: 0.002, IsPercentage: true},
		currency.XBTS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BVC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CHATX:      {Withdrawal: 10, IsPercentage: true},
		currency.BEEP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BEEZ:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BENJI:      {Withdrawal: 0.01, IsPercentage: true},
		currency.BERN:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PROFIT:     {Withdrawal: 0.01, IsPercentage: true},
		currency.BEST:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BGF:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BIGUP:      {Withdrawal: 0.002, IsPercentage: true},
		currency.BLRY:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BILL:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BNB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BIOB:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BIO:        {Withdrawal: 0.1, IsPercentage: true},
		currency.BIOS:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BPTN:       {Withdrawal: 10, IsPercentage: true},
		currency.BTCA:       {Withdrawal: 10, IsPercentage: true},
		currency.BA:         {Withdrawal: 0.002, IsPercentage: true},
		currency.BAC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BBT:        {Withdrawal: 10, IsPercentage: true},
		currency.BOSS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BRONZ:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CAT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BTD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BTC:        {Withdrawal: 0.0012, IsPercentage: true},
		currency.XBTC21:     {Withdrawal: 0.01, IsPercentage: true},
		currency.BCA:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BCH:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BCP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BCD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BTDOLL:     {Withdrawal: 0.01, IsPercentage: true},
		currency.GOD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BTG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LIZA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BTCRED:     {Withdrawal: 10, IsPercentage: true},
		currency.BTCS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BTU:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BUM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LITE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BCM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BCS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BTCU:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BM:         {Withdrawal: 10, IsPercentage: true},
		currency.BTCRY:      {Withdrawal: 0.002, IsPercentage: true},
		currency.BTCR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.HIRE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.STU:        {Withdrawal: 10, IsPercentage: true},
		currency.BITOK:      {Withdrawal: 0.0001, IsPercentage: true},
		currency.BITON:      {Withdrawal: 0.002, IsPercentage: true},
		currency.BPC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BPOK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BTP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.RNTB:       {Withdrawal: 10, IsPercentage: true},
		currency.BSH:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BTS:        {Withdrawal: 5, IsPercentage: true},
		currency.XBS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BITS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BST:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BXT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.VEG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VOLT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BTV:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BITZ:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BTZ:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BHC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BDC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.JACK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BS:         {Withdrawal: 0.01, IsPercentage: true},
		currency.BSTAR:      {Withdrawal: 0.01, IsPercentage: true},
		currency.BLAZR:      {Withdrawal: 0.01, IsPercentage: true},
		currency.BOD:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BLUE:       {Withdrawal: 10, IsPercentage: true},
		currency.BLU:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BLUS:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BMT:        {Withdrawal: 10, IsPercentage: true},
		currency.BOT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BOLI:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BOMB:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BON:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BOOM:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BOSON:      {Withdrawal: 0.01, IsPercentage: true},
		currency.BSC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BRH:        {Withdrawal: 10, IsPercentage: true},
		currency.BRAIN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.BRE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BTCM:       {Withdrawal: 0.1, IsPercentage: true},
		currency.BTCO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TALK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BUB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BUY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BUZZ:       {Withdrawal: 0.002, IsPercentage: true},
		currency.BTH:        {Withdrawal: 0.1, IsPercentage: true},
		currency.C0C0:       {Withdrawal: 0.002, IsPercentage: true},
		currency.CAB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CF:         {Withdrawal: 0.002, IsPercentage: true},
		currency.CLO:        {Withdrawal: 10, IsPercentage: true},
		currency.CAM:        {Withdrawal: 0.2, IsPercentage: true},
		currency.CD:         {Withdrawal: 0.002, IsPercentage: true},
		currency.CANN:       {Withdrawal: 0.2, IsPercentage: true},
		currency.CNNC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CPC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CST:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CAPT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.CARBON:     {Withdrawal: 0.01, IsPercentage: true},
		currency.CME:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CTK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CBD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CCC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CNT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XCE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CAG:        {Withdrawal: 1, IsPercentage: true},
		currency.CHRG:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CHAT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CHEMX:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CHESS:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CKS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CHILL:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CHIP:       {Withdrawal: 0.002, IsPercentage: true},
		currency.CHOOF:      {Withdrawal: 0.01, IsPercentage: true},
		currency.TIME:       {Withdrawal: 0.05, IsPercentage: true},
		currency.CRX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CIN:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CLAM:       {Withdrawal: 0.002, IsPercentage: true},
		currency.POLL:       {Withdrawal: 10, IsPercentage: true},
		currency.CLICK:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CLINT:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CLOAK:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CLUB:       {Withdrawal: 0.002, IsPercentage: true},
		currency.CLUD:       {Withdrawal: 0.01, IsPercentage: true},
		currency.COX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.COXST:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CFC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CTIC2:      {Withdrawal: 0.01, IsPercentage: true},
		currency.COIN:       {Withdrawal: 0.01, IsPercentage: true},
		currency.BTTF:       {Withdrawal: 0.002, IsPercentage: true},
		currency.C2:         {Withdrawal: 0.01, IsPercentage: true},
		currency.CAID:       {Withdrawal: 0.002, IsPercentage: true},
		currency.CL:         {Withdrawal: 10, IsPercentage: true},
		currency.CTIC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CXT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CHP:        {Withdrawal: 10, IsPercentage: true},
		currency.CV2:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CMT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.COC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.COMP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CMS:        {Withdrawal: 10, IsPercentage: true},
		currency.CONX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CCX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CLR:        {Withdrawal: 10, IsPercentage: true},
		currency.CORAL:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CORG:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CSMIC:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CMC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.COV:        {Withdrawal: 0.002, IsPercentage: true},
		currency.COVX:       {Withdrawal: 10, IsPercentage: true},
		currency.CRAB:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CRAFT:      {Withdrawal: 0.01, IsPercentage: true},
		currency.CRNK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CRAVE:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CRM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XCRE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CREDIT:     {Withdrawal: 0.002, IsPercentage: true},
		currency.CREVA:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CRIME:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CROC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CRC:        {Withdrawal: 10, IsPercentage: true},
		currency.CRW:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CRY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CBX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TKTX:       {Withdrawal: 10, IsPercentage: true},
		currency.CB:         {Withdrawal: 0.02, IsPercentage: true},
		currency.CIRC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.CCB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CDO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CG:         {Withdrawal: 0.01, IsPercentage: true},
		currency.CJ:         {Withdrawal: 0.01, IsPercentage: true},
		currency.CJC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CYT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CNX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CRPS:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PING:       {Withdrawal: 0.05, IsPercentage: true},
		currency.CS:         {Withdrawal: 0.002, IsPercentage: true},
		currency.CWXT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CCT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.CTL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.CURVES:     {Withdrawal: 0.002, IsPercentage: true},
		currency.CC:         {Withdrawal: 0.002, IsPercentage: true},
		currency.CYC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CYG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CYP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FUNK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.CZECO:      {Withdrawal: 0.01, IsPercentage: true},
		currency.DALC:       {Withdrawal: 0.1, IsPercentage: true},
		currency.DLISK:      {Withdrawal: 0.2, IsPercentage: true},
		currency.MOOND:      {Withdrawal: 0.002, IsPercentage: true},
		currency.DB:         {Withdrawal: 0.002, IsPercentage: true},
		currency.DCC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DCYP:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DETH:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DKC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DISK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.DRKT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DTT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DASH:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DASHS:      {Withdrawal: 0.01, IsPercentage: true},
		currency.DBTC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.DCT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DBET:       {Withdrawal: 10, IsPercentage: true},
		currency.DEC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DCR:        {Withdrawal: 0.05, IsPercentage: true},
		currency.DECR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DEA:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DPAY:       {Withdrawal: 0.01, IsPercentage: true},
		currency.DCRE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DC:         {Withdrawal: 0.002, IsPercentage: true},
		currency.DES:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DEM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DXC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DCK:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DGB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CUBE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DGMS:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DBG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DGCS:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DBLK:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DGD:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DIME:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DIRT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DVD:        {Withdrawal: 10, IsPercentage: true},
		currency.DMT:        {Withdrawal: 10, IsPercentage: true},
		currency.NOTE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DOGE:       {Withdrawal: 100, IsPercentage: true},
		currency.DGORE:      {Withdrawal: 0.002, IsPercentage: true},
		currency.DLC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DRT:        {Withdrawal: 0.1, IsPercentage: true},
		currency.DOTA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.DOX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DRA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DFT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XDB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DRM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DRZ:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DRACO:      {Withdrawal: 0.002, IsPercentage: true},
		currency.DBIC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DUB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GUM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.DUR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DUST:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DUX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.DXO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ECN:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EDR2:       {Withdrawal: 0.002, IsPercentage: true},
		currency.EA:         {Withdrawal: 0.002, IsPercentage: true},
		currency.EAGS:       {Withdrawal: 0.002, IsPercentage: true},
		currency.EMT:        {Withdrawal: 10, IsPercentage: true},
		currency.EBONUS:     {Withdrawal: 0.001, IsPercentage: true},
		currency.ECCHI:      {Withdrawal: 0.01, IsPercentage: true},
		currency.EKO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ECLI:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ECOB:       {Withdrawal: 3, IsPercentage: true},
		currency.ECO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EDIT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.EDRC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.EDC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EGAME:      {Withdrawal: 0.01, IsPercentage: true},
		currency.EGG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EGO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ELC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ELCO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ECA:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EPC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ELE:        {Withdrawal: 0.005, IsPercentage: true},
		currency.ONE337:     {Withdrawal: 0.002, IsPercentage: true},
		currency.EMB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EMC:        {Withdrawal: 0.02, IsPercentage: true},
		currency.EPY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EMPC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.EMP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ENE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EET:        {Withdrawal: 10, IsPercentage: true},
		currency.XNG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EGMA:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ENTER:      {Withdrawal: 0.01, IsPercentage: true},
		currency.ETRUST:     {Withdrawal: 0.002, IsPercentage: true},
		currency.EOS:        {Withdrawal: 10, IsPercentage: true},
		currency.EQL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EQM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EQT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ERR:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ESC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ESP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ENT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ETCO:       {Withdrawal: 0.2, IsPercentage: true},
		currency.DOGETH:     {Withdrawal: 0.002, IsPercentage: true},
		currency.ETH:        {Withdrawal: 0.005, IsPercentage: true},
		currency.ECASH:      {Withdrawal: 0.1, IsPercentage: true},
		currency.ETC:        {Withdrawal: 0.005, IsPercentage: true},
		currency.ELITE:      {Withdrawal: 0.05, IsPercentage: true},
		currency.ETHS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ETL:        {Withdrawal: 1, IsPercentage: true},
		currency.ETZ:        {Withdrawal: 10, IsPercentage: true},
		currency.EUC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EURC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.EUROPE:     {Withdrawal: 0.01, IsPercentage: true},
		currency.EVA:        {Withdrawal: 0.01, IsPercentage: true},
		currency.EGC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EOC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EVIL:       {Withdrawal: 0.002, IsPercentage: true},
		currency.EVO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EXB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.EXIT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.EXP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XT:         {Withdrawal: 0.01, IsPercentage: true},
		currency.F16:        {Withdrawal: 0.01, IsPercentage: true},
		currency.FADE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.DROP:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FAZZ:       {Withdrawal: 0.01, IsPercentage: true},
		currency.FX:         {Withdrawal: 0.01, IsPercentage: true},
		currency.FIDEL:      {Withdrawal: 0.01, IsPercentage: true},
		currency.FIDGT:      {Withdrawal: 0.01, IsPercentage: true},
		currency.FIND:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FPC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.FIRE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FFC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FRST:       {Withdrawal: 0.01, IsPercentage: true},
		currency.FIST:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FIT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.FLX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.FLVR:       {Withdrawal: 0.01, IsPercentage: true},
		currency.FLY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FONZ:       {Withdrawal: 0.002, IsPercentage: true},
		currency.XFCX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FOREX:      {Withdrawal: 0.01, IsPercentage: true},
		currency.FRN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FRK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FRWC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.FGZ:        {Withdrawal: 0.01, IsPercentage: true},
		currency.FRE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FRDC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FJC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.FURY:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FSN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.FCASH:      {Withdrawal: 0.002, IsPercentage: true},
		currency.FTO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.FUZZ:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GAKH:       {Withdrawal: 0.01, IsPercentage: true},
		currency.GBT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GAME:       {Withdrawal: 0.01, IsPercentage: true},
		currency.GML:        {Withdrawal: 0.2, IsPercentage: true},
		currency.UNITS:      {Withdrawal: 0.01, IsPercentage: true},
		currency.FOUR20G:    {Withdrawal: 0.01, IsPercentage: true},
		currency.GSY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GENIUS:     {Withdrawal: 0.002, IsPercentage: true},
		currency.GEN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GEO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GER:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GSR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SPKTR:      {Withdrawal: 0.002, IsPercentage: true},
		currency.GIFT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.WTT:        {Withdrawal: 10, IsPercentage: true},
		currency.GHS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GIG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GOT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XGTC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.GIZ:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GLO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GCR:        {Withdrawal: 0.002, IsPercentage: true},
		currency.BSTY:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GLC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GSX:        {Withdrawal: 0.02, IsPercentage: true},
		currency.GNO:        {Withdrawal: 0.05, IsPercentage: true},
		currency.GOAT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GO:         {Withdrawal: 0.01, IsPercentage: true},
		currency.GB:         {Withdrawal: 0.01, IsPercentage: true},
		currency.GFL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MNTP:       {Withdrawal: 10, IsPercentage: true},
		currency.GP:         {Withdrawal: 0.002, IsPercentage: true},
		currency.GNT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.GLUCK:      {Withdrawal: 0.002, IsPercentage: true},
		currency.GOON:       {Withdrawal: 0.01, IsPercentage: true},
		currency.GTFO:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GOTX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.GPU:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GRF:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GRAM:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GRAV:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GBIT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GREED:      {Withdrawal: 0.002, IsPercentage: true},
		currency.GE:         {Withdrawal: 0.002, IsPercentage: true},
		currency.GREENF:     {Withdrawal: 0.01, IsPercentage: true},
		currency.GRE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GREXIT:     {Withdrawal: 0.002, IsPercentage: true},
		currency.GMCX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.GROW:       {Withdrawal: 0.01, IsPercentage: true},
		currency.GSM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GT:         {Withdrawal: 0.01, IsPercentage: true},
		currency.NLG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HKN:        {Withdrawal: 10, IsPercentage: true},
		currency.HAC:        {Withdrawal: 0.05, IsPercentage: true},
		currency.HALLO:      {Withdrawal: 0.01, IsPercentage: true},
		currency.HAMS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HCC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HPC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HMC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HAWK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HAZE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.HZT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.HDG:        {Withdrawal: 0.1, IsPercentage: true},
		currency.HEDG:       {Withdrawal: 0.002, IsPercentage: true},
		currency.HEEL:       {Withdrawal: 0.002, IsPercentage: true},
		currency.HMP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PLAY:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HXX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XHI:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HVCO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HTC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MINH:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HODL:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HON:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HOPE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.HQX:        {Withdrawal: 10, IsPercentage: true},
		currency.HSP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.HTML5:      {Withdrawal: 0.002, IsPercentage: true},
		currency.HMQ:        {Withdrawal: 0.01, IsPercentage: true},
		currency.HYPERX:     {Withdrawal: 0.01, IsPercentage: true},
		currency.HPS:        {Withdrawal: 10, IsPercentage: true},
		currency.IOC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.IBANK:      {Withdrawal: 0.01, IsPercentage: true},
		currency.IBITS:      {Withdrawal: 0.002, IsPercentage: true},
		currency.ICASH:      {Withdrawal: 0.002, IsPercentage: true},
		currency.ICOB:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ICN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ICON:       {Withdrawal: 0.01, IsPercentage: true},
		currency.IETH:       {Withdrawal: 0.1, IsPercentage: true},
		currency.ILM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.IMPS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.NKA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.INCP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.IN:         {Withdrawal: 0.01, IsPercentage: true},
		currency.INC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.IMS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.IND:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XIN:        {Withdrawal: 0.01, IsPercentage: true},
		currency.IFLT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.INFX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.INGT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.INPAY:      {Withdrawal: 0.01, IsPercentage: true},
		currency.INSANE:     {Withdrawal: 0.01, IsPercentage: true},
		currency.INXT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.IFT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.INV:        {Withdrawal: 0.01, IsPercentage: true},
		currency.IVZ:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ILT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.IONX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ISL:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ITI:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ING:        {Withdrawal: 10, IsPercentage: true},
		currency.IEC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.IW:         {Withdrawal: 0.01, IsPercentage: true},
		currency.IXC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.IXT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.JPC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.JANE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.JWL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.JNT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.JIF:        {Withdrawal: 0.002, IsPercentage: true},
		currency.JOBS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.JOCKER:     {Withdrawal: 0.01, IsPercentage: true},
		currency.JW:         {Withdrawal: 0.01, IsPercentage: true},
		currency.JOK:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XJO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.KGB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.KARMC:      {Withdrawal: 0.01, IsPercentage: true},
		currency.KARMA:      {Withdrawal: 0.002, IsPercentage: true},
		currency.KASHH:      {Withdrawal: 0.01, IsPercentage: true},
		currency.KAT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.KC:         {Withdrawal: 0.002, IsPercentage: true},
		currency.KICK:       {Withdrawal: 0.05, IsPercentage: true},
		currency.KIDS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.KIN:        {Withdrawal: 10, IsPercentage: true},
		currency.KNC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.KISS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.KOBO:       {Withdrawal: 0.002, IsPercentage: true},
		currency.TP1:        {Withdrawal: 0.002, IsPercentage: true},
		currency.KRAK:       {Withdrawal: 0.002, IsPercentage: true},
		currency.KGC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.KTK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.KR:         {Withdrawal: 0.005, IsPercentage: true},
		currency.KUBO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.KURT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.KUSH:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LANA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LTH:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LAZ:        {Withdrawal: 0.2, IsPercentage: true},
		currency.LEA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LEAF:       {Withdrawal: 0.002, IsPercentage: true},
		currency.LENIN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.LEPEN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.LIR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LVG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LGBTQ:      {Withdrawal: 0.002, IsPercentage: true},
		currency.LHC:        {Withdrawal: 10, IsPercentage: true},
		currency.EXT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LBTC:       {Withdrawal: 0.1, IsPercentage: true},
		currency.LSD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LIMX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.LTD:        {Withdrawal: 0.0000002, IsPercentage: true},
		currency.LINDA:      {Withdrawal: 0.01, IsPercentage: true},
		currency.LKC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LSK:        {Withdrawal: 0.2, IsPercentage: true},
		currency.LBTCX:      {Withdrawal: 0.01, IsPercentage: true},
		currency.LTC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LCC:        {Withdrawal: 1, IsPercentage: true},
		currency.LTCU:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LTCR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.LDOGE:      {Withdrawal: 0.002, IsPercentage: true},
		currency.LTS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LIV:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LIZI:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LOC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.LOCX:       {Withdrawal: 10, IsPercentage: true},
		currency.LOOK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LRC:        {Withdrawal: 0.05, IsPercentage: true},
		currency.LOOT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.XLTCG:      {Withdrawal: 0.002, IsPercentage: true},
		currency.BASH:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LUCKY:      {Withdrawal: 0.002, IsPercentage: true},
		currency.L7S:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LDM:        {Withdrawal: 0.05, IsPercentage: true},
		currency.LUMI:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LUNA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.LUN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.LC:         {Withdrawal: 0.01, IsPercentage: true},
		currency.LUX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MCRN:       {Withdrawal: 0.01, IsPercentage: true},
		currency.XMG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MMXIV:      {Withdrawal: 0.02, IsPercentage: true},
		currency.MAT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MAO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MAPC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.MRB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MXT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MARV:       {Withdrawal: 0.01, IsPercentage: true},
		currency.MARX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.MCAR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.MM:         {Withdrawal: 0.002, IsPercentage: true},
		currency.GUP:        {Withdrawal: 0.05, IsPercentage: true},
		currency.MVC:        {Withdrawal: 0.05, IsPercentage: true},
		currency.MAVRO:      {Withdrawal: 0.01, IsPercentage: true},
		currency.MAX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MAZE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.MBIT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.MCOIN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.MPRO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.XMS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MLITE:      {Withdrawal: 0.01, IsPercentage: true},
		currency.MLNC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.MENTAL:     {Withdrawal: 0.01, IsPercentage: true},
		currency.MERGEC:     {Withdrawal: 0.01, IsPercentage: true},
		currency.MTLMC3:     {Withdrawal: 0.002, IsPercentage: true},
		currency.METAL:      {Withdrawal: 0.002, IsPercentage: true},
		currency.AMM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MDT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MUU:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MILO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.MND:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XMINE:      {Withdrawal: 0.002, IsPercentage: true},
		currency.MNM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XNM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MIRO:       {Withdrawal: 10, IsPercentage: true},
		currency.MIS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MMXVI:      {Withdrawal: 0.01, IsPercentage: true},
		currency.MGO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MOIN:       {Withdrawal: 0.002, IsPercentage: true},
		currency.MOJO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TAB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MCO:        {Withdrawal: 0.005, IsPercentage: true},
		currency.MONETA:     {Withdrawal: 0.002, IsPercentage: true},
		currency.MUE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MONEY:      {Withdrawal: 0.01, IsPercentage: true},
		currency.MRP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MOTO:       {Withdrawal: 0.002, IsPercentage: true},
		currency.MULTI:      {Withdrawal: 0.01, IsPercentage: true},
		currency.MST:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MVR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.MYSTIC:     {Withdrawal: 0.002, IsPercentage: true},
		currency.WISH:       {Withdrawal: 10, IsPercentage: true},
		currency.NKT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NMC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NAT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ENAU:       {Withdrawal: 10, IsPercentage: true},
		currency.NAV:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NEBU:       {Withdrawal: 0.002, IsPercentage: true},
		currency.NEF:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XEM:        {Withdrawal: 20, IsPercentage: true},
		currency.NBIT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.NETKO:      {Withdrawal: 0.01, IsPercentage: true},
		currency.NTM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NETC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.NEU:        {Withdrawal: 10, IsPercentage: true},
		currency.NRC:        {Withdrawal: 1, IsPercentage: true},
		currency.NTK:        {Withdrawal: 10, IsPercentage: true},
		currency.NTRN:       {Withdrawal: 0.002, IsPercentage: true},
		currency.NEVA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.NIC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NKC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NYC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NZC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NICE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.NET:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NDOGE:      {Withdrawal: 0.002, IsPercentage: true},
		currency.XTR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.N2O:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NIXON:      {Withdrawal: 0.01, IsPercentage: true},
		currency.NOC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NODC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.NODES:      {Withdrawal: 0.002, IsPercentage: true},
		currency.NODX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.NLC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NLC2:       {Withdrawal: 0.01, IsPercentage: true},
		currency.NOO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NVC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NPC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.NUBIS:      {Withdrawal: 0.002, IsPercentage: true},
		currency.NUKE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.N7:         {Withdrawal: 0.01, IsPercentage: true},
		currency.NUM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.NMR:        {Withdrawal: 0.05, IsPercentage: true},
		currency.NXE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.OBS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.OCEAN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.OCOW:       {Withdrawal: 0.01, IsPercentage: true},
		currency.EIGHT88:    {Withdrawal: 0.02, IsPercentage: true},
		currency.OCC:        {Withdrawal: 0.02, IsPercentage: true},
		currency.OK:         {Withdrawal: 0.002, IsPercentage: true},
		currency.ODNT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.FLAV:       {Withdrawal: 0.002, IsPercentage: true},
		currency.OLIT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.OLYMP:      {Withdrawal: 0.01, IsPercentage: true},
		currency.OMA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.OMC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.OMG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ONEK:       {Withdrawal: 0.05, IsPercentage: true},
		currency.ONX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XPO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.OPAL:       {Withdrawal: 0.2, IsPercentage: true},
		currency.OTN:        {Withdrawal: 0.1, IsPercentage: true},
		currency.OP:         {Withdrawal: 0.01, IsPercentage: true},
		currency.OPES:       {Withdrawal: 0.002, IsPercentage: true},
		currency.OPTION:     {Withdrawal: 0.002, IsPercentage: true},
		currency.ORLY:       {Withdrawal: 0.01, IsPercentage: true},
		currency.OS76:       {Withdrawal: 0.002, IsPercentage: true},
		currency.OZC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.P7C:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PAC:        {Withdrawal: 1, IsPercentage: true},
		currency.PAK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PAL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PND:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PINKX:      {Withdrawal: 0.01, IsPercentage: true},
		currency.POPPY:      {Withdrawal: 0.01, IsPercentage: true},
		currency.DUO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PARA:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PKB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GENE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PARTY:      {Withdrawal: 0.01, IsPercentage: true},
		currency.PYN:        {Withdrawal: 10, IsPercentage: true},
		currency.XPY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CON:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PAYP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.PPC:        {Withdrawal: 0.2, IsPercentage: true},
		currency.GUESS:      {Withdrawal: 10, IsPercentage: true},
		currency.PEN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PTA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PEO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PSB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XPD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PXL:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PHR:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PIE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PIO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PIPR:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SKULL:      {Withdrawal: 0.01, IsPercentage: true},
		currency.PIVX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PLANET:     {Withdrawal: 0.002, IsPercentage: true},
		currency.PNC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XPTX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.PLNC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PLU:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XPS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.POKE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.PLBT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.POLY:       {Withdrawal: 0.002, IsPercentage: true},
		currency.POM:        {Withdrawal: 0.001, IsPercentage: true},
		currency.PONZ2:      {Withdrawal: 0.01, IsPercentage: true},
		currency.PONZI:      {Withdrawal: 0.01, IsPercentage: true},
		currency.XSP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PPT:        {Withdrawal: 10, IsPercentage: true},
		currency.XPC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PEX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TRON:       {Withdrawal: 0.002, IsPercentage: true},
		currency.POST:       {Withdrawal: 0.01, IsPercentage: true},
		currency.POSW:       {Withdrawal: 0.01, IsPercentage: true},
		currency.PWR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.POWER:      {Withdrawal: 0.002, IsPercentage: true},
		currency.PRE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PRS:        {Withdrawal: 10, IsPercentage: true},
		currency.PXI:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PEXT:       {Withdrawal: 10, IsPercentage: true},
		currency.PRIMU:      {Withdrawal: 0.01, IsPercentage: true},
		currency.PRX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PRM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PRIX:       {Withdrawal: 10, IsPercentage: true},
		currency.XPRO:       {Withdrawal: 0.002, IsPercentage: true},
		currency.PCM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PROC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.NANOX:      {Withdrawal: 0.01, IsPercentage: true},
		currency.VRP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.PTY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PSI:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PSY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.PULSE:      {Withdrawal: 0.01, IsPercentage: true},
		currency.PUPA:       {Withdrawal: 0.01, IsPercentage: true},
		currency.PURE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.VIDZ:       {Withdrawal: 0.01, IsPercentage: true},
		currency.PUTIN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.PX:         {Withdrawal: 0.1, IsPercentage: true},
		currency.QTM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.QTZ:        {Withdrawal: 0.002, IsPercentage: true},
		currency.QBC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XQN:        {Withdrawal: 0.02, IsPercentage: true},
		currency.RBBT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RAC:        {Withdrawal: 10, IsPercentage: true},
		currency.RADI:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RAD:        {Withdrawal: 0.002, IsPercentage: true},
		currency.RAI:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XRA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.RATIO:      {Withdrawal: 0.002, IsPercentage: true},
		currency.RCN:        {Withdrawal: 0.01, IsPercentage: true},
		currency.REA:        {Withdrawal: 10, IsPercentage: true},
		currency.RCX:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RDD:        {Withdrawal: 0.002, IsPercentage: true},
		currency.REE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.REC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.REQ:        {Withdrawal: 10, IsPercentage: true},
		currency.RMS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.RBIT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RNC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.R:          {Withdrawal: 1, IsPercentage: true},
		currency.REV:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RH:         {Withdrawal: 0.01, IsPercentage: true},
		currency.XRL:        {Withdrawal: 1, IsPercentage: true},
		currency.RICE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.RICHX:      {Withdrawal: 0.002, IsPercentage: true},
		currency.RID:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RIDE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RBT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.RING:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RIO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RISE:       {Withdrawal: 0.2, IsPercentage: true},
		currency.ROCKET:     {Withdrawal: 0.01, IsPercentage: true},
		currency.RPC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ROS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ROYAL:      {Withdrawal: 0.01, IsPercentage: true},
		currency.RSGP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RBIES:      {Withdrawal: 0.002, IsPercentage: true},
		currency.RUBIT:      {Withdrawal: 0.002, IsPercentage: true},
		currency.RBY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RUC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RUPX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.RUP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.RUST:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SFE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SLS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SMSR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.RONIN:      {Withdrawal: 0.002, IsPercentage: true},
		currency.SAN:        {Withdrawal: 0.05, IsPercentage: true},
		currency.STV:        {Withdrawal: 0.002, IsPercentage: true},
		currency.HIFUN:      {Withdrawal: 0.002, IsPercentage: true},
		currency.MAD:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SANDG:      {Withdrawal: 0.002, IsPercentage: true},
		currency.STO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SCAN:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SCITW:      {Withdrawal: 0.002, IsPercentage: true},
		currency.SCRPT:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SCRT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SED:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SEEDS:      {Withdrawal: 0.002, IsPercentage: true},
		currency.B2X:        {Withdrawal: 0.1, IsPercentage: true},
		currency.SEL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SLFI:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SSC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SMBR:       {Withdrawal: 0.2, IsPercentage: true},
		currency.SEN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SENT:       {Withdrawal: 10, IsPercentage: true},
		currency.SRNT:       {Withdrawal: 10, IsPercentage: true},
		currency.SEV:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SP:         {Withdrawal: 0.01, IsPercentage: true},
		currency.SXC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.GELD:       {Withdrawal: 0.05, IsPercentage: true},
		currency.SHDW:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SDC:        {Withdrawal: 0.02, IsPercentage: true},
		currency.SAK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SHRP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SHELL:      {Withdrawal: 0.002, IsPercentage: true},
		currency.SH:         {Withdrawal: 0.01, IsPercentage: true},
		currency.SHORTY:     {Withdrawal: 0.01, IsPercentage: true},
		currency.SHREK:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SHRM:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SIB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SIGT:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SLCO:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SIGU:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SIX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SJW:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SKB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SW:         {Withdrawal: 0.01, IsPercentage: true},
		currency.SLEEP:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SLING:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SMART:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SMC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SMT:        {Withdrawal: 10, IsPercentage: true},
		currency.SMF:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SOCC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SCL:        {Withdrawal: 0.05, IsPercentage: true},
		currency.SDAO:       {Withdrawal: 10, IsPercentage: true},
		currency.SOLAR:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SOLO:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SCT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SONG:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SNM:        {Withdrawal: 0.05, IsPercentage: true},
		currency.ALTCOM:     {Withdrawal: 0.01, IsPercentage: true},
		currency.SPHTX:      {Withdrawal: 10, IsPercentage: true},
		currency.SOUL:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SPC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SPACE:      {Withdrawal: 0.002, IsPercentage: true},
		currency.SBT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SPEC:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SPX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SCS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.SPORT:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SPT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SPR:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SPEX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SQL:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SBIT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.STHR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.STALIN:     {Withdrawal: 0.01, IsPercentage: true},
		currency.STAR:       {Withdrawal: 0.01, IsPercentage: true},
		currency.STA:        {Withdrawal: 0.01, IsPercentage: true},
		currency.START:      {Withdrawal: 0.02, IsPercentage: true},
		currency.STP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SNT:        {Withdrawal: 10, IsPercentage: true},
		currency.PNK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.STEPS:      {Withdrawal: 0.002, IsPercentage: true},
		currency.STK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.STONK:      {Withdrawal: 0.01, IsPercentage: true},
		currency.STORJ:      {Withdrawal: 0.05, IsPercentage: true},
		currency.STORM:      {Withdrawal: 10, IsPercentage: true},
		currency.STS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.STRP:       {Withdrawal: 0.002, IsPercentage: true},
		currency.STY:        {Withdrawal: 10, IsPercentage: true},
		currency.SUB:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XMT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SNC:        {Withdrawal: 1, IsPercentage: true},
		currency.SSTC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SBTC:       {Withdrawal: 0.1, IsPercentage: true},
		currency.SUPER:      {Withdrawal: 0.002, IsPercentage: true},
		currency.SRND:       {Withdrawal: 0.002, IsPercentage: true},
		currency.STRB:       {Withdrawal: 0.02, IsPercentage: true},
		currency.M1:         {Withdrawal: 0.002, IsPercentage: true},
		currency.SPM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.BUCKS:      {Withdrawal: 0.002, IsPercentage: true},
		currency.TOKEN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.SWT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.SWEET:      {Withdrawal: 0.002, IsPercentage: true},
		currency.SWING:      {Withdrawal: 0.002, IsPercentage: true},
		currency.CHSB:       {Withdrawal: 10, IsPercentage: true},
		currency.SIC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SDP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XSY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.SYNX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.SNRG:       {Withdrawal: 0.002, IsPercentage: true},
		currency.SYS:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TAG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TAGR:       {Withdrawal: 0.002, IsPercentage: true},
		currency.TAJ:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TAK:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TAKE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TAM:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XTO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TAP:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TLE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TSE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TLEX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TAXI:       {Withdrawal: 10, IsPercentage: true},
		currency.TCN:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TDFB:       {Withdrawal: 0.002, IsPercentage: true},
		currency.TEAM:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TECH:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TEC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TEK:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TB:         {Withdrawal: 0.002, IsPercentage: true},
		currency.TLX:        {Withdrawal: 10, IsPercentage: true},
		currency.TELL:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TENNET:     {Withdrawal: 0.002, IsPercentage: true},
		currency.PAY:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TES:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TRA:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TGS:        {Withdrawal: 10, IsPercentage: true},
		currency.XVE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TCR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.GCC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.MAY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.THOM:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TIA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TIDE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TNT:        {Withdrawal: 0.05, IsPercentage: true},
		currency.TIE:        {Withdrawal: 10, IsPercentage: true},
		currency.TIT:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TTC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TODAY:      {Withdrawal: 0.01, IsPercentage: true},
		currency.TBX:        {Withdrawal: 10, IsPercentage: true},
		currency.TKN:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TDS:        {Withdrawal: 10, IsPercentage: true},
		currency.TLOSH:      {Withdrawal: 0.01, IsPercentage: true},
		currency.TOKC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TMRW:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TOOL:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TCX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TOT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TX:         {Withdrawal: 0.002, IsPercentage: true},
		currency.TRANSF:     {Withdrawal: 0.002, IsPercentage: true},
		currency.TRAP:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TBCX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.TRICK:      {Withdrawal: 0.002, IsPercentage: true},
		currency.TPG:        {Withdrawal: 0.01, IsPercentage: true},
		currency.TRX:        {Withdrawal: 300, IsPercentage: true},
		currency.TFL:        {Withdrawal: 10, IsPercentage: true},
		currency.TRUMP:      {Withdrawal: 0.002, IsPercentage: true},
		currency.TNG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TUR:        {Withdrawal: 0.002, IsPercentage: true},
		currency.TWERK:      {Withdrawal: 0.002, IsPercentage: true},
		currency.TWIST:      {Withdrawal: 0.002, IsPercentage: true},
		currency.TWO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.UCASH:      {Withdrawal: 10, IsPercentage: true},
		currency.UAE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XBU:        {Withdrawal: 0.01, IsPercentage: true},
		currency.UBQ:        {Withdrawal: 0.01, IsPercentage: true},
		currency.U:          {Withdrawal: 0.002, IsPercentage: true},
		currency.UDOWN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.GAIN:       {Withdrawal: 0.01, IsPercentage: true},
		currency.USC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.UMC:        {Withdrawal: 0.1, IsPercentage: true},
		currency.UNF:        {Withdrawal: 0.01, IsPercentage: true},
		currency.UNIFY:      {Withdrawal: 0.01, IsPercentage: true},
		currency.UKG:        {Withdrawal: 10, IsPercentage: true},
		currency.USDE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.UBTC:       {Withdrawal: 0.1, IsPercentage: true},
		currency.UIS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.UNIT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.UNI:        {Withdrawal: 0.01, IsPercentage: true},
		currency.UXC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.URC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XUP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.UFR:        {Withdrawal: 10, IsPercentage: true},
		currency.URO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.UTLE:       {Withdrawal: 0.002, IsPercentage: true},
		currency.VAL:        {Withdrawal: 0.02, IsPercentage: true},
		currency.VPRC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.VAPOR:      {Withdrawal: 0.002, IsPercentage: true},
		currency.VCOIN:      {Withdrawal: 0.002, IsPercentage: true},
		currency.VEC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VEC2:       {Withdrawal: 0.01, IsPercentage: true},
		currency.VLT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.VENE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.VNTX:       {Withdrawal: 0.01, IsPercentage: true},
		currency.VTN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XVG:        {Withdrawal: 0.002, IsPercentage: true},
		currency.CRED:       {Withdrawal: 10, IsPercentage: true},
		currency.VERS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.VTC:        {Withdrawal: 0.2, IsPercentage: true},
		currency.VTX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VIA:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VTY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.VIP:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VISIO:      {Withdrawal: 0.01, IsPercentage: true},
		currency.VK:         {Withdrawal: 2, IsPercentage: true},
		currency.VOL:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VOYA:       {Withdrawal: 0.002, IsPercentage: true},
		currency.VPN:        {Withdrawal: 0.002, IsPercentage: true},
		currency.VSL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XVS:        {Withdrawal: 0.01, IsPercentage: true},
		currency.VTL:        {Withdrawal: 0.01, IsPercentage: true},
		currency.VULC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.VVI:        {Withdrawal: 10, IsPercentage: true},
		currency.WGR:        {Withdrawal: 0.01, IsPercentage: true},
		currency.WAM:        {Withdrawal: 0.01, IsPercentage: true},
		currency.WARP:       {Withdrawal: 0.002, IsPercentage: true},
		currency.WASH:       {Withdrawal: 0.01, IsPercentage: true},
		currency.WAVES:      {Withdrawal: 0.002, IsPercentage: true},
		currency.WGO:        {Withdrawal: 0.01, IsPercentage: true},
		currency.WAY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.WCASH:      {Withdrawal: 0.01, IsPercentage: true},
		currency.WEALTH:     {Withdrawal: 0.002, IsPercentage: true},
		currency.WEEK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.WHO:        {Withdrawal: 0.5, IsPercentage: true},
		currency.WIC:        {Withdrawal: 0.05, IsPercentage: true},
		currency.WBB:        {Withdrawal: 0.002, IsPercentage: true},
		currency.WINE:       {Withdrawal: 0.01, IsPercentage: true},
		currency.WINK:       {Withdrawal: 0.01, IsPercentage: true},
		currency.WISC:       {Withdrawal: 0.01, IsPercentage: true},
		currency.WITCH:      {Withdrawal: 0.01, IsPercentage: true},
		currency.WMC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.WOMEN:      {Withdrawal: 0.01, IsPercentage: true},
		currency.WOK:        {Withdrawal: 0.01, IsPercentage: true},
		currency.WRC:        {Withdrawal: 10, IsPercentage: true},
		currency.WRT:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XCO:        {Withdrawal: 0.002, IsPercentage: true},
		currency.X2:         {Withdrawal: 0.002, IsPercentage: true},
		currency.XNX:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XAU:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XAV:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XDE2:       {Withdrawal: 0.002, IsPercentage: true},
		currency.XDE:        {Withdrawal: 0.002, IsPercentage: true},
		currency.XIOS:       {Withdrawal: 0.01, IsPercentage: true},
		currency.XOC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.XSSX:       {Withdrawal: 0.002, IsPercentage: true},
		currency.XBY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.YAC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.YMC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.YAY:        {Withdrawal: 0.01, IsPercentage: true},
		currency.YBC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.YES:        {Withdrawal: 0.01, IsPercentage: true},
		currency.YOB2X:      {Withdrawal: 0.01, IsPercentage: true},
		currency.YOVI:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ZYD:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ZEC:        {Withdrawal: 0.02, IsPercentage: true},
		currency.ZECD:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ZEIT:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ZENI:       {Withdrawal: 0.01, IsPercentage: true},
		currency.ZET2:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ZET:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ZMC:        {Withdrawal: 0.002, IsPercentage: true},
		currency.ZIRK:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ZLQ:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ZNE:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ZONTO:      {Withdrawal: 0.05, IsPercentage: true},
		currency.ZOOM:       {Withdrawal: 0.002, IsPercentage: true},
		currency.ZRC:        {Withdrawal: 0.01, IsPercentage: true},
		currency.ZUR:        {Withdrawal: 0.002, IsPercentage: true},
	},
}
