// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Portfolio is an object representing the database table.
type Portfolio struct {
	PortfolioID int64   `boil:"portfolio_id" json:"portfolio_id" toml:"portfolio_id" yaml:"portfolio_id"`
	ConfigID    int64   `boil:"config_id" json:"config_id" toml:"config_id" yaml:"config_id"`
	CoinAddress string  `boil:"coin_address" json:"coin_address" toml:"coin_address" yaml:"coin_address"`
	CoinType    string  `boil:"coin_type" json:"coin_type" toml:"coin_type" yaml:"coin_type"`
	Balance     float64 `boil:"balance" json:"balance" toml:"balance" yaml:"balance"`
	Description string  `boil:"description" json:"description" toml:"description" yaml:"description"`

	R *portfolioR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L portfolioL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PortfolioColumns = struct {
	PortfolioID string
	ConfigID    string
	CoinAddress string
	CoinType    string
	Balance     string
	Description string
}{
	PortfolioID: "portfolio_id",
	ConfigID:    "config_id",
	CoinAddress: "coin_address",
	CoinType:    "coin_type",
	Balance:     "balance",
	Description: "description",
}

// portfolioR is where relationships are stored.
type portfolioR struct {
}

// portfolioL is where Load methods for each relationship are stored.
type portfolioL struct{}

var (
	portfolioColumns               = []string{"portfolio_id", "config_id", "coin_address", "coin_type", "balance", "description"}
	portfolioColumnsWithoutDefault = []string{"portfolio_id", "config_id", "coin_address", "coin_type", "balance", "description"}
	portfolioColumnsWithDefault    = []string{}
	portfolioPrimaryKeyColumns     = []string{"portfolio_id"}
)

type (
	// PortfolioSlice is an alias for a slice of pointers to Portfolio.
	// This should generally be used opposed to []Portfolio.
	PortfolioSlice []*Portfolio

	portfolioQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	portfolioType                 = reflect.TypeOf(&Portfolio{})
	portfolioMapping              = queries.MakeStructMapping(portfolioType)
	portfolioPrimaryKeyMapping, _ = queries.BindMapping(portfolioType, portfolioMapping, portfolioPrimaryKeyColumns)
	portfolioInsertCacheMut       sync.RWMutex
	portfolioInsertCache          = make(map[string]insertCache)
	portfolioUpdateCacheMut       sync.RWMutex
	portfolioUpdateCache          = make(map[string]updateCache)
	portfolioUpsertCacheMut       sync.RWMutex
	portfolioUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single portfolio record from the query, and panics on error.
func (q portfolioQuery) OneP() *Portfolio {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single portfolio record from the query.
func (q portfolioQuery) One() (*Portfolio, error) {
	o := &Portfolio{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for portfolio")
	}

	return o, nil
}

// AllP returns all Portfolio records from the query, and panics on error.
func (q portfolioQuery) AllP() PortfolioSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Portfolio records from the query.
func (q portfolioQuery) All() (PortfolioSlice, error) {
	var o []*Portfolio

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Portfolio slice")
	}

	return o, nil
}

// CountP returns the count of all Portfolio records in the query, and panics on error.
func (q portfolioQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Portfolio records in the query.
func (q portfolioQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count portfolio rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q portfolioQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q portfolioQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if portfolio exists")
	}

	return count > 0, nil
}

// PortfoliosG retrieves all records.
func PortfoliosG(mods ...qm.QueryMod) portfolioQuery {
	return Portfolios(boil.GetDB(), mods...)
}

// Portfolios retrieves all the records using an executor.
func Portfolios(exec boil.Executor, mods ...qm.QueryMod) portfolioQuery {
	mods = append(mods, qm.From("\"portfolio\""))
	return portfolioQuery{NewQuery(exec, mods...)}
}

// FindPortfolioG retrieves a single record by ID.
func FindPortfolioG(portfolioID int64, selectCols ...string) (*Portfolio, error) {
	return FindPortfolio(boil.GetDB(), portfolioID, selectCols...)
}

// FindPortfolioGP retrieves a single record by ID, and panics on error.
func FindPortfolioGP(portfolioID int64, selectCols ...string) *Portfolio {
	retobj, err := FindPortfolio(boil.GetDB(), portfolioID, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindPortfolio retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPortfolio(exec boil.Executor, portfolioID int64, selectCols ...string) (*Portfolio, error) {
	portfolioObj := &Portfolio{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"portfolio\" where \"portfolio_id\"=$1", sel,
	)

	q := queries.Raw(exec, query, portfolioID)

	err := q.Bind(portfolioObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from portfolio")
	}

	return portfolioObj, nil
}

// FindPortfolioP retrieves a single record by ID with an executor, and panics on error.
func FindPortfolioP(exec boil.Executor, portfolioID int64, selectCols ...string) *Portfolio {
	retobj, err := FindPortfolio(exec, portfolioID, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Portfolio) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Portfolio) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Portfolio) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Portfolio) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no portfolio provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(portfolioColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	portfolioInsertCacheMut.RLock()
	cache, cached := portfolioInsertCache[key]
	portfolioInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			portfolioColumns,
			portfolioColumnsWithDefault,
			portfolioColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(portfolioType, portfolioMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(portfolioType, portfolioMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"portfolio\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"portfolio\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into portfolio")
	}

	if !cached {
		portfolioInsertCacheMut.Lock()
		portfolioInsertCache[key] = cache
		portfolioInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single Portfolio record. See Update for
// whitelist behavior description.
func (o *Portfolio) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Portfolio record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Portfolio) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Portfolio, and panics on error.
// See Update for whitelist behavior description.
func (o *Portfolio) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Portfolio.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Portfolio) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	portfolioUpdateCacheMut.RLock()
	cache, cached := portfolioUpdateCache[key]
	portfolioUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			portfolioColumns,
			portfolioPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update portfolio, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"portfolio\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, portfolioPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(portfolioType, portfolioMapping, append(wl, portfolioPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update portfolio row")
	}

	if !cached {
		portfolioUpdateCacheMut.Lock()
		portfolioUpdateCache[key] = cache
		portfolioUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q portfolioQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q portfolioQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for portfolio")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o PortfolioSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o PortfolioSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o PortfolioSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PortfolioSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), portfolioPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"portfolio\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, portfolioPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in portfolio slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Portfolio) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Portfolio) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Portfolio) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Portfolio) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no portfolio provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(portfolioColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	portfolioUpsertCacheMut.RLock()
	cache, cached := portfolioUpsertCache[key]
	portfolioUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			portfolioColumns,
			portfolioColumnsWithDefault,
			portfolioColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			portfolioColumns,
			portfolioPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert portfolio, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(portfolioPrimaryKeyColumns))
			copy(conflict, portfolioPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"portfolio\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(portfolioType, portfolioMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(portfolioType, portfolioMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert portfolio")
	}

	if !cached {
		portfolioUpsertCacheMut.Lock()
		portfolioUpsertCache[key] = cache
		portfolioUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single Portfolio record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Portfolio) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Portfolio record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Portfolio) DeleteG() error {
	if o == nil {
		return errors.New("models: no Portfolio provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Portfolio record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Portfolio) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Portfolio record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Portfolio) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Portfolio provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), portfolioPrimaryKeyMapping)
	sql := "DELETE FROM \"portfolio\" WHERE \"portfolio_id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from portfolio")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q portfolioQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q portfolioQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no portfolioQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from portfolio")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o PortfolioSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o PortfolioSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Portfolio slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o PortfolioSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PortfolioSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Portfolio slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), portfolioPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"portfolio\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, portfolioPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from portfolio slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Portfolio) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Portfolio) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Portfolio) ReloadG() error {
	if o == nil {
		return errors.New("models: no Portfolio provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Portfolio) Reload(exec boil.Executor) error {
	ret, err := FindPortfolio(exec, o.PortfolioID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *PortfolioSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *PortfolioSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PortfolioSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty PortfolioSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PortfolioSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	portfolios := PortfolioSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), portfolioPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"portfolio\".* FROM \"portfolio\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, portfolioPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&portfolios)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PortfolioSlice")
	}

	*o = portfolios

	return nil
}

// PortfolioExists checks if the Portfolio row exists.
func PortfolioExists(exec boil.Executor, portfolioID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"portfolio\" where \"portfolio_id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, portfolioID)
	}

	row := exec.QueryRow(sql, portfolioID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if portfolio exists")
	}

	return exists, nil
}

// PortfolioExistsG checks if the Portfolio row exists.
func PortfolioExistsG(portfolioID int64) (bool, error) {
	return PortfolioExists(boil.GetDB(), portfolioID)
}

// PortfolioExistsGP checks if the Portfolio row exists. Panics on error.
func PortfolioExistsGP(portfolioID int64) bool {
	e, err := PortfolioExists(boil.GetDB(), portfolioID)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// PortfolioExistsP checks if the Portfolio row exists. Panics on error.
func PortfolioExistsP(exec boil.Executor, portfolioID int64) bool {
	e, err := PortfolioExists(exec, portfolioID)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
