package currency

import "errors"

// symbols map holds the currency name and symbol mappings
var symbols = map[*code]string{
	ALL.C:  "Lek",
	AFN.C:  "؋",
	ARS.C:  "$",
	AWG.C:  "ƒ",
	AUD.C:  "$",
	AZN.C:  "ман",
	BSD.C:  "$",
	BBD.C:  "$",
	BYN.C:  "Br",
	BZD.C:  "BZ$",
	BMD.C:  "$",
	BOB.C:  "$b",
	BAM.C:  "KM",
	BWP.C:  "P",
	BGN.C:  "лв",
	BRL.C:  "R$",
	BND.C:  "$",
	KHR.C:  "៛",
	CAD.C:  "$",
	KYD.C:  "$",
	CLP.C:  "$",
	CNY.C:  "¥",
	COP.C:  "$",
	CRC.C:  "₡",
	HRK.C:  "kn",
	CUP.C:  "₱",
	CZK.C:  "Kč",
	DKK.C:  "kr",
	DOP.C:  "RD$",
	XCD.C:  "$",
	EGP.C:  "£",
	SVC.C:  "$",
	EUR.C:  "€",
	FKP.C:  "£",
	FJD.C:  "$",
	GHS.C:  "¢",
	GIP.C:  "£",
	GTQ.C:  "Q",
	GGP.C:  "£",
	GYD.C:  "$",
	HNL.C:  "L",
	HKD.C:  "$",
	HUF.C:  "Ft",
	ISK.C:  "kr",
	INR.C:  "₹",
	IDR.C:  "Rp",
	IRR.C:  "﷼",
	IMP.C:  "£",
	ILS.C:  "₪",
	JMD.C:  "J$",
	JPY.C:  "¥",
	JEP.C:  "£",
	KZT.C:  "лв",
	KPW.C:  "₩",
	KRW.C:  "₩",
	KGS.C:  "лв",
	LAK.C:  "₭",
	LBP.C:  "£",
	LRD.C:  "$",
	MKD.C:  "ден",
	MYR.C:  "RM",
	MUR.C:  "₨",
	MXN.C:  "$",
	MNT.C:  "₮",
	MZN.C:  "MT",
	NAD.C:  "$",
	NPR.C:  "₨",
	ANG.C:  "ƒ",
	NZD.C:  "$",
	NIO.C:  "C$",
	NGN.C:  "₦",
	NOK.C:  "kr",
	OMR.C:  "﷼",
	PKR.C:  "₨",
	PAB.C:  "B/.",
	PYG.C:  "Gs",
	PEN.C:  "S/.",
	PHP.C:  "₱",
	PLN.C:  "zł",
	QAR.C:  "﷼",
	RON.C:  "lei",
	RUB.C:  "₽",
	RUR.C:  "₽",
	SHP.C:  "£",
	SAR.C:  "﷼",
	RSD.C:  "Дин.",
	SCR.C:  "₨",
	SGD.C:  "$",
	SBD.C:  "$",
	SOS.C:  "S",
	ZAR.C:  "R",
	LKR.C:  "₨",
	SEK.C:  "kr",
	CHF.C:  "CHF",
	SRD.C:  "$",
	SYP.C:  "£",
	TWD.C:  "NT$",
	THB.C:  "฿",
	TTD.C:  "TT$",
	TRY.C:  "₺",
	TVD.C:  "$",
	UAH.C:  "₴",
	GBP.C:  "£",
	USD.C:  "$",
	USDT.C: "$",
	UYU.C:  "$U",
	UZS.C:  "лв",
	VEF.C:  "Bs",
	VND.C:  "₫",
	YER.C:  "﷼",
	ZWD.C:  "Z$",
}

// GetSymbolByCurrencyName returns a currency symbol
func GetSymbolByCurrencyName(currency Code) (string, error) {
	result, ok := symbols[currency.C]
	if !ok {
		return "", errors.New("currency symbol not found")
	}
	return result, nil
}
