package currency

import (
	"time"

	"github.com/thrasher-corp/gocryptotrader/currency/coinmarketcap"
)

// MainConfiguration is the main configuration from the config.json file
type MainConfiguration struct {
	ForexProviders         []FXSettings
	CryptocurrencyProvider coinmarketcap.Settings
	Cryptocurrencies       Currencies
	CurrencyPairFormat     interface{}
	FiatDisplayCurrency    Code
	CurrencyDelay          time.Duration
	FxRateDelay            time.Duration
}

// BotOverrides defines a bot overriding factor for quick running currency
// subsystems
type BotOverrides struct {
	Coinmarketcap       bool
	FxCurrencyConverter bool
	FxCurrencyLayer     bool
	FxFixer             bool
	FxOpenExchangeRates bool
}

// CoinmarketcapSettings refers to settings
type CoinmarketcapSettings coinmarketcap.Settings

// SystemsSettings defines incoming system settings
type SystemsSettings struct {
	Coinmarketcap     coinmarketcap.Settings
	Currencyconverter FXSettings
	Currencylayer     FXSettings
	Fixer             FXSettings
	Openexchangerates FXSettings
}

// FXSettings defines foreign exchange requester settings
type FXSettings struct {
	Name             string        `json:"name"`
	Enabled          bool          `json:"enabled"`
	Verbose          bool          `json:"verbose"`
	RESTPollingDelay time.Duration `json:"restPollingDelay"`
	APIKey           string        `json:"apiKey"`
	APIKeyLvl        int           `json:"apiKeyLvl"`
	PrimaryProvider  bool          `json:"primaryProvider"`
}

// File defines a full currency file generated by the currency storage
// analysis system
type File struct {
	LastMainUpdate time.Time `json:"lastMainUpdate"`
	Cryptocurrency []Item    `json:"cryptocurrencies"`
	FiatCurrency   []Item    `json:"fiatCurrencies"`
	UnsetCurrency  []Item    `json:"unsetCurrencies"`
	Contracts      []Item    `json:"contracts"`
	Token          []Item    `json:"tokens"`
}

// Const here are packaged defined delimiters
const (
	Underscore   = "_"
	Dash         = "-"
	ForwardSlash = "/"
	Colon        = ":"
)

// delimiters is a delimiter list
var delimiters = []string{Underscore, Dash, ForwardSlash, Colon}

// Slice interface defines a slice of currency items
type Slice interface {
	Strings() []string
	Join() string
	Format(delimiter, index string, uppercase bool) Slice
	UnmarshalJSON(d []byte) error
	MarshalJSON() ([]byte, error)
	Contains(check Pair, exact bool) bool
	RemovePairsByFilter(filter Code) Slice
	Remove(pair Singular) Slice
	Add(pair Singular) Slice
	FindDifferences(pairs Slice) (newPairs, removedPairs Pairs)
	GetRandomPair() Singular
}

// Singular defines a singular currency item
type Singular interface {
	String() string
	Lower() Singular
	Upper() Singular
	UnmarshalJSON(d []byte) error
	MarshalJSON() ([]byte, error)
	Format(delimiter string, uppercase bool) Singular
	Equal(item Singular) bool
	EqualIncludeReciprocal(item Singular) bool
	IsCryptoPair() bool
	IsCryptoFiatPair() bool
	IsFiatPair() bool
	IsInvalid() bool
	Swap() Singular
	IsEmpty() bool
	ContainsCurrency(item Singular) bool
}
