package currency

import "errors"

// GetSymbolByCurrencyName returns a currency symbol
func GetSymbolByCurrencyName(currency Code) (string, error) {
	result, ok := symbols[currency.Item]
	if !ok {
		return "", errors.New("currency symbol not found")
	}
	return result, nil
}

// symbols map holds the currency name and symbol mappings
var symbols = map[*Item]string{
	ALL.Item:  "Lek",
	AFN.Item:  "؋",
	ARS.Item:  "$",
	AWG.Item:  "ƒ",
	AUD.Item:  "$",
	AZN.Item:  "ман",
	BSD.Item:  "$",
	BBD.Item:  "$",
	BYN.Item:  "Br",
	BZD.Item:  "BZ$",
	BMD.Item:  "$",
	BOB.Item:  "$b",
	BAM.Item:  "KM",
	BWP.Item:  "P",
	BGN.Item:  "лв",
	BRL.Item:  "R$",
	BND.Item:  "$",
	KHR.Item:  "៛",
	CAD.Item:  "$",
	KYD.Item:  "$",
	CLP.Item:  "$",
	CNY.Item:  "¥",
	COP.Item:  "$",
	CRC.Item:  "₡",
	HRK.Item:  "kn",
	CUP.Item:  "₱",
	CZK.Item:  "Kč",
	DKK.Item:  "kr",
	DOP.Item:  "RD$",
	XCD.Item:  "$",
	EGP.Item:  "£",
	SVC.Item:  "$",
	EUR.Item:  "€",
	FKP.Item:  "£",
	FJD.Item:  "$",
	GHS.Item:  "¢",
	GIP.Item:  "£",
	GTQ.Item:  "Q",
	GGP.Item:  "£",
	GYD.Item:  "$",
	HNL.Item:  "L",
	HKD.Item:  "$",
	HUF.Item:  "Ft",
	ISK.Item:  "kr",
	INR.Item:  "₹",
	IDR.Item:  "Rp",
	IRR.Item:  "﷼",
	IMP.Item:  "£",
	ILS.Item:  "₪",
	JMD.Item:  "J$",
	JPY.Item:  "¥",
	JEP.Item:  "£",
	KZT.Item:  "лв",
	KPW.Item:  "₩",
	KRW.Item:  "₩",
	KGS.Item:  "лв",
	LAK.Item:  "₭",
	LBP.Item:  "£",
	LRD.Item:  "$",
	MKD.Item:  "ден",
	MYR.Item:  "RM",
	MUR.Item:  "₨",
	MXN.Item:  "$",
	MNT.Item:  "₮",
	MZN.Item:  "MT",
	NAD.Item:  "$",
	NPR.Item:  "₨",
	ANG.Item:  "ƒ",
	NZD.Item:  "$",
	NIO.Item:  "C$",
	NGN.Item:  "₦",
	NOK.Item:  "kr",
	OMR.Item:  "﷼",
	PKR.Item:  "₨",
	PAB.Item:  "B/.",
	PYG.Item:  "Gs",
	PEN.Item:  "S/.",
	PHP.Item:  "₱",
	PLN.Item:  "zł",
	QAR.Item:  "﷼",
	RON.Item:  "lei",
	RUB.Item:  "₽",
	RUR.Item:  "₽",
	SHP.Item:  "£",
	SAR.Item:  "﷼",
	RSD.Item:  "Дин.",
	SCR.Item:  "₨",
	SGD.Item:  "$",
	SBD.Item:  "$",
	SOS.Item:  "S",
	ZAR.Item:  "R",
	LKR.Item:  "₨",
	SEK.Item:  "kr",
	CHF.Item:  "CHF",
	SRD.Item:  "$",
	SYP.Item:  "£",
	TWD.Item:  "NT$",
	THB.Item:  "฿",
	TTD.Item:  "TT$",
	TRY.Item:  "₺",
	TVD.Item:  "$",
	UAH.Item:  "₴",
	GBP.Item:  "£",
	USD.Item:  "$",
	USDT.Item: "$",
	UYU.Item:  "$U",
	UZS.Item:  "лв",
	VEF.Item:  "Bs",
	VND.Item:  "₫",
	YER.Item:  "﷼",
	ZWD.Item:  "Z$",
}
