name: configs-versions-lint
on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
      - 'dependabot/**'
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  lint:
    name: config versions lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
    - name: Check config versions are continuous
      run: go test ./config/versions/ -tags config_versions -run Continuity