name: golangci-lint
on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
      - 'dependabot/**'
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .golangci-lint-version
      - name: golangci-lint (udecimal)
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .golangci-lint-version
          args: --build-tags=udecimal_on
