name: misc
on: [push, pull_request]
jobs:
  lint:
    name: miscellaneous checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Run miscellaneous checks
      run: ./scripts/misc_checks.sh
        

