name: misc
on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
      - 'dependabot/**'
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  lint:
    name: miscellaneous checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Run miscellaneous checks
      run: ./scripts/misc_checks.sh

    - name: Lint Markdown
      run: make markdownlint

  workflow-lint:
    name: workflow lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Record Go cache key
      run: echo "workflow-lint" > .go-cache-key

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
        cache-dependency-path: |
          go.sum
          .go-cache-key

    - name: Install shellcheck
      run: |
        pipx install shellcheck-py==0.11.0.1
        pipx environment --value PIPX_BIN_DIR >> "$GITHUB_PATH"

    - name: Lint workflows and shell scripts
      run: make workflow_lint
